#!/usr/bin/env python3
"""Fills the German translation file with the strings below.

The .ts files themselves are generated by lupdate (`cmake --build build
--target update_translations`). This script only supplies the German text, so
regenerating the .ts after a code change does not mean retyping everything —
run lupdate, then run this.

Strings not listed here are left untranslated, and Qt then falls back to the
English source, which is the right behaviour for a missing entry.

    python3 tools/fill_german.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
TS_FILE = ROOT / "translations" / "leolink_de.ts"

# Source string → German. Plain text, no XML escaping: that is applied on write.
GERMAN: dict[str, str] = {
    # ── menus ──
    "&File": "&Datei",
    "&View": "&Ansicht",
    "&Help": "&Hilfe",
    "&Cameras…": "&Kameras…",
    "&Save snapshots…": "&Standbilder speichern…",
    "&Event log…": "&Ereignisprotokoll…",
    "Open &recordings folder": "&Aufnahmeordner öffnen",
    "&Quit": "&Beenden",
    "&Full screen": "&Vollbild",
    "Show &menu bar": "&Menüleiste anzeigen",
    "Show &toolbar": "&Werkzeugleiste anzeigen",
    "Show status &bar": "&Statusleiste anzeigen",
    "Hide window &decoration": "Fenster&rahmen ausblenden",
    "&Online handbook": "&Online-Handbuch",
    "&Protocol notes": "&Protokollnotizen",
    "&Report a problem": "&Problem melden",
    "&About leolink": "Ü&ber leolink",
    "Main": "Haupt",

    # ── main window ──
    "Ready": "Bereit",
    "Grid view": "Gitteransicht",
    "No cameras configured": "Keine Kameras eingerichtet",
    "Nothing to capture": "Nichts aufzunehmen",
    "Save snapshots to": "Standbilder speichern unter",
    "Double-click to return to the grid": "Doppelklick führt zurück zum Gitter",
    "Cannot save": "Speichern nicht möglich",
    "Settings could not be written to %1.":
        "Die Einstellungen konnten nicht nach %1 geschrieben werden.",
    "Cannot create %1": "%1 kann nicht angelegt werden",
    "Recording %1": "Nimmt auf: %1",
    "Saved %1": "Gespeichert: %1",
    "Motion at %1": "Bewegung bei %1",
    "Motion detected": "Bewegung erkannt",
    "Could not run the motion command for %1":
        "Der Bewegungsbefehl für %1 ließ sich nicht ausführen",
    "leolink is still running": "leolink läuft weiter",
    "Cameras keep recording. Use the tray icon to come back.":
        "Die Kameras nehmen weiter auf. Über das Symbol im Systemabschnitt "
        "kommen Sie zurück.",
    "Show window": "Fenster anzeigen",
    "Cameras…": "Kameras…",
    "Quit": "Beenden",
    "Welcome to leolink": "Willkommen bei leolink",
    "<b>No cameras are configured yet.</b>":
        "<b>Es ist noch keine Kamera eingerichtet.</b>",
    "Add a camera with its address, user name and password. leolink talks to "
    "the camera directly on your network — no cloud account is involved."
    "<p>The handbook covers what each option does.":
        "Legen Sie eine Kamera mit Adresse, Benutzername und Passwort an. "
        "leolink spricht direkt im eigenen Netz mit der Kamera — ohne "
        "Cloud-Konto.<p>Was die einzelnen Optionen tun, steht im Handbuch.",
    "Add camera…": "Kamera hinzufügen…",
    "Open handbook": "Handbuch öffnen",
    "About leolink": "Über leolink",
    "<b>%1</b>": "<b>%1</b>",
    "<h3>leolink %1</h3><p>A native Linux client for Reolink cameras.</p>"
    "<p>Speaks the camera's own protocols directly: HTTP API, RTSP and ONVIF "
    "on the local network, and Reolink's P2P service when you want to reach a "
    "camera from elsewhere.</p>"
    "<p><a href=\"%2\">Handbook</a> · "
    "<a href=\"https://github.com/tombueng/leolink\">Source</a></p>"
    "<p>Not affiliated with or endorsed by Reolink.</p>":
        "<h3>leolink %1</h3><p>Ein nativer Linux-Client für Reolink-Kameras.</p>"
        "<p>Spricht direkt die Protokolle der Kamera: HTTP-API, RTSP und ONVIF "
        "im lokalen Netz, und Reolinks P2P-Dienst, wenn eine Kamera von "
        "auswärts erreichbar sein soll.</p>"
        "<p><a href=\"%2\">Handbuch</a> · "
        "<a href=\"https://github.com/tombueng/leolink\">Quelltext</a></p>"
        "<p>Nicht mit Reolink verbunden und nicht von Reolink unterstützt.</p>",
    "No cameras configured yet.\n\nUse “Cameras…” to add one.":
        "Noch keine Kamera eingerichtet.\n\nÜber „Kameras…“ eine anlegen.",

    # ── tile ──
    "connecting…": "verbinde…",
    "main stream": "Hauptstream",
    "sub stream": "Substream",
    "no host configured": "keine Adresse eingetragen",
    "cannot open stream": "Stream lässt sich nicht öffnen",
    "libmpv unavailable": "libmpv nicht verfügbar",
    "player init failed": "Wiedergabe ließ sich nicht starten",
    "MOTION": "BEWEGUNG",
    "Mute this camera": "Diese Kamera stummschalten",
    "Volume": "Lautstärke",
    "Camera settings": "Kameraeinstellungen",

    # ── settings: general ──
    "Settings": "Einstellungen",
    "Cameras": "Kameras",
    "Layout": "Anordnung",
    "Events": "Ereignisse",
    "Window": "Fenster",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Remove camera": "Kamera entfernen",
    "Remove “%1” from the list?": "„%1“ aus der Liste entfernen?",
    "New camera": "Neue Kamera",
    "Name": "Name",
    "Host": "Adresse",
    "User": "Benutzer",
    "Password": "Passwort",
    "Password command": "Passwortbefehl",
    "UID": "UID",
    "Stream": "Stream",
    "Transport": "Übertragung",
    "192.168.1.10 or camera.lan": "192.168.1.10 oder kamera.lan",
    "optional, for P2P access": "optional, für P2P-Zugriff",
    "optional: pass show reolink/hall": "optional: pass show reolink/flur",
    "If set, this command runs and its output is used as the password. Keeps "
    "the secret out of the configuration file.":
        "Ist das gesetzt, wird dieser Befehl ausgeführt und seine Ausgabe als "
        "Passwort verwendet. So steht das Geheimnis nicht in der "
        "Konfigurationsdatei.",
    "Sub stream (low bandwidth)": "Substream (wenig Bandbreite)",
    "Main stream (full resolution)": "Hauptstream (volle Auflösung)",
    "RTSP": "RTSP",
    "HTTP-FLV (lower latency)": "HTTP-FLV (geringere Latenz)",
    "Use HTTPS for the control API": "HTTPS für die Steuer-API verwenden",
    "Show this camera": "Diese Kamera anzeigen",
    "Test connection": "Verbindung testen",
    "Contacting %1…": "Kontaktiere %1…",
    "Enter a host first.": "Bitte zuerst eine Adresse eintragen.",
    "Incomplete camera": "Unvollständige Kamera",
    "“%1” has no host address.": "„%1“ hat keine Adresse.",
    "%1 — firmware %2, %3 channel(s)": "%1 — Firmware %2, %3 Kanäle",

    # ── settings: discovery ──
    "Scan network…": "Netzwerk durchsuchen…",
    "Ask the network which ONVIF cameras are present. This sends one multicast "
    "probe; devices that stay quiet are never contacted.":
        "Fragt im Netz nach vorhandenen ONVIF-Kameras. Dabei geht eine einzige "
        "Multicast-Anfrage hinaus; Geräte, die schweigen, werden nicht "
        "kontaktiert.",
    "Looking for cameras…": "Suche Kameras…",
    "Stop": "Abbrechen",
    "Cameras found": "Kameras gefunden",
    "Add which one?": "Welche hinzufügen?",
    "No cameras found": "Keine Kameras gefunden",
    "No ONVIF device answered.\n\nCameras only reply if ONVIF is switched on, "
    "and the probe does not cross routers or most VPNs. You can still add a "
    "camera by typing its address.":
        "Kein ONVIF-Gerät hat geantwortet.\n\nKameras antworten nur, wenn "
        "ONVIF eingeschaltet ist; die Anfrage überquert weder Router noch die "
        "meisten VPNs. Sie können die Kamera weiterhin von Hand über ihre "
        "Adresse eintragen.",
    "unnamed device": "unbenanntes Gerät",
    " (Reolink)": " (Reolink)",
    "Cannot open a UDP socket for discovery.":
        "Für die Suche ließ sich kein UDP-Socket öffnen.",

    # ── settings: layout ──
    "Grid size": "Gittergröße",
    "Columns": "Spalten",
    "Rows": "Zeilen",
    "Column": "Spalte",
    "Row": "Zeile",
    "Row span": "Zeilen überspannen",
    "Column span": "Spalten überspannen",
    "automatic": "automatisch",
    "Position of the selected camera": "Position der gewählten Kamera",
    "Leave row and column on “automatic” to let cameras fill the grid in "
    "order. Spans let one camera cover several cells.":
        "Bleiben Zeile und Spalte auf „automatisch“, füllen die Kameras das "
        "Gitter der Reihe nach. Über die Überspannung belegt eine Kamera "
        "mehrere Felder.",

    # ── settings: events ──
    "Watch cameras for motion (ONVIF push)":
        "Kameras auf Bewegung überwachen (ONVIF-Push)",
    "The camera reports motion when it happens, rather than leolink asking "
    "once a second.":
        "Die Kamera meldet Bewegung, sobald sie auftritt — leolink muss nicht "
        "im Sekundentakt nachfragen.",
    "Run command": "Befehl ausführen",
    "notify-send \"Motion at %n\"": "notify-send \"Bewegung bei %n\"",
    "Runs when this camera reports motion.\n"
    "%n camera name · %h host · %t timestamp · %f recording file":
        "Wird ausgeführt, wenn diese Kamera Bewegung meldet.\n"
        "%n Kameraname · %h Adresse · %t Zeitstempel · %f Aufnahmedatei",
    "Record while motion lasts": "Während der Bewegung aufnehmen",
    "Records on this computer from the live stream, so it works even when the "
    "camera has no SD card fitted.":
        "Nimmt auf diesem Rechner aus dem Livestream auf — funktioniert also "
        "auch ohne SD-Karte in der Kamera.",
    "Keep recording after": "Nachlauf der Aufnahme",
    " s": " s",
    "Selected camera": "Gewählte Kamera",
    "All cameras": "Alle Kameras",
    "Recordings folder": "Aufnahmeordner",
    "Browse…": "Durchsuchen…",
    "Recordings are written as Matroska without re-encoding: the picture keeps "
    "the camera's original quality and the CPU stays nearly idle.":
        "Aufnahmen werden als Matroska ohne Neukodierung geschrieben: das Bild "
        "behält die Originalqualität der Kamera, und der Prozessor bleibt "
        "nahezu unbelastet.",

    # ── settings: window ──
    "Appearance": "Darstellung",
    "Show menu bar": "Menüleiste anzeigen",
    "Show toolbar": "Werkzeugleiste anzeigen",
    "Show status bar": "Statusleiste anzeigen",
    "Hide window decoration": "Fensterrahmen ausblenden",
    "Ctrl+M toggles this at any time.": "Strg+M schaltet das jederzeit um.",
    "For wall displays. Ctrl+Shift+D toggles it.":
        "Für Wanddisplays. Strg+Umschalt+D schaltet um.",
    "Notification area": "Systemabschnitt",
    "Show an icon in the notification area":
        "Symbol im Systemabschnitt anzeigen",
    "Closing the window hides it instead of quitting":
        "Schließen blendet das Fenster aus, statt zu beenden",
    "Minimising hides the window to the tray":
        "Minimieren blendet das Fenster in den Systemabschnitt aus",
    "On motion": "Bei Bewegung",
    "Bring the window up when motion is detected":
        "Fenster bei erkannter Bewegung hervorholen",
    "Come back as": "Zurückkommen als",
    "Previous size": "Vorherige Größe",
    "Full screen": "Vollbild",
    "Language": "Sprache",
    "System language": "Systemsprache",
    "Takes effect after restarting leolink.":
        "Wird nach einem Neustart von leolink wirksam.",
    "Menu bar hidden": "Menüleiste ausgeblendet",
    "With both the menu bar and the toolbar hidden, press Ctrl+M to bring the "
    "menu back.":
        "Sind Menü- und Werkzeugleiste beide ausgeblendet, holt Strg+M das "
        "Menü zurück.",

    # ── event log ──
    "Event log": "Ereignisprotokoll",
    "Camera:": "Kamera:",
    "Show:": "Anzeigen:",
    "All events": "Alle Ereignisse",
    "Motion": "Bewegung",
    "With recording": "Mit Aufnahme",
    "Refresh": "Aktualisieren",
    "When": "Wann",
    "Camera": "Kamera",
    "Event": "Ereignis",
    "Media": "Medien",
    "video": "Video",
    "image": "Bild",
    " + image": " + Bild",
    "no preview": "keine Vorschau",
    "recording only": "nur Aufnahme",
    "no events recorded yet": "noch keine Ereignisse aufgezeichnet",
    "Recording: %1%2": "Aufnahme: %1%2",
    " (file missing)": " (Datei fehlt)",
    "Image: %1": "Bild: %1",
    "Open recording": "Aufnahme öffnen",
    "Open image": "Bild öffnen",
    "Nothing to open": "Nichts zu öffnen",
    "The file for this event is no longer there.":
        "Die Datei zu diesem Ereignis ist nicht mehr vorhanden.",
    "Clear log…": "Protokoll leeren…",
    "Clear event log": "Ereignisprotokoll leeren",
    "Delete the whole event history?\n\nRecorded videos and images stay on "
    "disk — only the log is cleared.":
        "Den gesamten Ereignisverlauf löschen?\n\nAufgezeichnete Videos und "
        "Bilder bleiben erhalten — nur das Protokoll wird geleert.",

    # ── event actions ──
    "Command": "Befehl",
    "could not be started": "ließ sich nicht starten",
    "Webhook": "Webhook",
    "invalid URL": "ungültige Adresse",
    "Webhook → %1": "Webhook → %1",
    "%1 failed: %2": "%1 fehlgeschlagen: %2",
    "Event log…": "Ereignisprotokoll…",
    "MQTT broker or topic not set.":
        "MQTT-Broker oder Topic nicht gesetzt.",
    "MQTT broker did not respond.": "Der MQTT-Broker hat nicht geantwortet.",
    "MQTT: %1": "MQTT: %1",
    "MQTT: unexpected reply from the broker.":
        "MQTT: unerwartete Antwort des Brokers.",
    "MQTT refused the connection: %1":
        "MQTT hat die Verbindung abgelehnt: %1",

    # ── decoding ──
    "Video": "Video",
    "Decoding": "Dekodierung",
    "Hardware, fastest": "Hardware, am schnellsten",
    "Hardware, with frame copy": "Hardware, mit Bildkopie",
    "Software only": "Nur Software",
    "Hardware decoding keeps the processor free and is the right choice for "
    "main-stream resolutions.\n\n"
    "If the picture shows green blocks or stalls, pick “with frame copy”: it "
    "still decodes on the GPU but copies each frame to main memory, which some "
    "drivers need when the video sits inside another window.":
        "Hardware-Dekodierung hält den Prozessor frei und ist bei "
        "Hauptstream-Auflösungen die richtige Wahl.\n\n"
        "Zeigt das Bild grüne Flächen oder stockt es, wählen Sie „mit "
        "Bildkopie“: dekodiert weiterhin auf der GPU, kopiert aber jedes Bild "
        "in den Hauptspeicher — das brauchen manche Treiber, wenn das Video in "
        "einem anderen Fenster eingebettet ist.",
    "Favour low latency over smoothness":
        "Niedrige Latenz wichtiger als flüssige Wiedergabe",
    "Keeps buffering to a minimum. Turn this off if a high-bitrate stream "
    "stutters over a busy network.":
        "Hält die Pufferung minimal. Bei ruckelnden Streams mit hoher Bitrate "
        "in einem ausgelasteten Netz besser abschalten.",

    # ── frameless hint ──
    "Drag the strip under a camera to move the window. Ctrl+Shift+D brings the "
    "frame back, Ctrl+M the menu.":
        "Zum Verschieben die Leiste unter einer Kamera ziehen. Strg+Umschalt+D "
        "holt den Rahmen zurück, Strg+M das Menü.",

    # ── camera settings dialog ──
    "%1 — camera settings": "%1 — Kameraeinstellungen",
    "Reading settings from %1…": "Lese Einstellungen von %1…",
    "Apply to camera": "Auf Kamera anwenden",
    "Main stream": "Hauptstream",
    "Sub stream": "Substream",
    "Resolution": "Auflösung",
    "Frame rate": "Bildrate",
    "Bit rate (kbit/s)": "Bitrate (kbit/s)",
    "H.264 profile": "H.264-Profil",
    "Higher means better picture and more network traffic. The camera only "
    "offers the rates it can actually sustain.":
        "Höher heißt besseres Bild und mehr Netzlast. Die Kamera bietet nur "
        "die Raten an, die sie auch halten kann.",
    "These change the camera itself, so every client sees the result. The "
    "choices come from the camera and differ per model.":
        "Das verändert die Kamera selbst — jeder Client sieht das Ergebnis. "
        "Die Auswahl kommt von der Kamera und unterscheidet sich je Modell.",
    "Picture": "Bild",
    "Brightness": "Helligkeit",
    "Contrast": "Kontrast",
    "Saturation": "Sättigung",
    "Sharpness": "Schärfe",
    "Hue": "Farbton",
    "Ready.": "Bereit.",
    "Writing to the camera…": "Schreibe auf die Kamera…",
    "Nothing to write.": "Nichts zu schreiben.",
    "Saved. Changing the encoder restarts the stream, so the picture may drop "
    "out for a moment.":
        "Gespeichert. Eine Encoder-Änderung startet den Stream neu, das Bild "
        "kann daher kurz aussetzen.",

    # ── recording ──
    "&Record all cameras": "Alle Kameras &aufnehmen",
    "Record this camera": "Diese Kamera aufnehmen",
    "Stop recording": "Aufnahme beenden",
    "Recording all cameras": "Nehme alle Kameras auf",
    "Recording stopped": "Aufnahme beendet",
    "Recording started": "Aufnahme gestartet",
    "Could not start recording %1":
        "Aufnahme von %1 ließ sich nicht starten",

    # ── recorder ──
    "%1: %2": "%1: %2",
    "ffmpeg is not installed, so recording is unavailable.":
        "ffmpeg ist nicht installiert, Aufnahmen sind daher nicht möglich.",
    "No stream address for %1.": "Keine Stream-Adresse für %1.",
    "Recording failed: %1": "Aufnahme fehlgeschlagen: %1",
    "Recording produced no data (ffmpeg exit %1).":
        "Die Aufnahme enthält keine Daten (ffmpeg-Rückgabewert %1).",
    "Could not start ffmpeg.": "ffmpeg ließ sich nicht starten.",

    # ── custom source ──
    "Custom URL": "Eigene Adresse",
    "Any address libmpv can open. Use this for cameras from other makers, an "
    "NVR stream, or a local file.":
        "Jede Adresse, die libmpv öffnen kann — für Kameras anderer Hersteller, "
        "einen NVR-Stream oder eine lokale Datei.",

    # ── detectors ──
    "ffmpeg is not installed, so motion detection is unavailable.":
        "ffmpeg ist nicht installiert, Bewegungserkennung daher nicht möglich.",
    "ffmpeg is not installed, so sound detection is unavailable.":
        "ffmpeg ist nicht installiert, Geräuscherkennung daher nicht möglich.",
    "Motion detection stopped: %1": "Bewegungserkennung beendet: %1",
    "Sound detection stopped: %1": "Geräuscherkennung beendet: %1",
    "Could not start ffmpeg for motion detection.":
        "ffmpeg für die Bewegungserkennung ließ sich nicht starten.",
    "Could not start ffmpeg for sound detection.":
        "ffmpeg für die Geräuscherkennung ließ sich nicht starten.",
    "Sound detected": "Geräusch erkannt",
    "%1 at %2": "%1 bei %2",
    "Detection": "Erkennung",
    "Motion comes from": "Bewegung meldet",
    "The camera reports it (ONVIF)": "Die Kamera selbst (ONVIF)",
    "leolink watches the picture": "leolink beobachtet das Bild",
    "Either of the two": "Beides",
    "Do not watch": "Nicht überwachen",
    "Cameras that report motion themselves cost nothing to watch.\n\n"
    "Analysing the picture here works with any camera, including ones that "
    "report nothing, but opens a second connection to the sub stream for each.":
        "Kameras, die Bewegung selbst melden, kosten nichts.\n\n"
        "Die Bildanalyse hier funktioniert mit jeder Kamera, auch mit solchen, "
        "die nichts melden — öffnet aber je Kamera eine zweite Verbindung zum "
        "Substream.",
    "Motion zones…": "Bewegungszonen…",
    "Choose which parts of the picture are watched. Only applies when leolink "
    "analyses the picture itself.":
        "Legt fest, welche Bildbereiche überwacht werden. Gilt nur, wenn "
        "leolink das Bild selbst analysiert.",
    "Sensitivity": "Empfindlichkeit",
    "How much a spot in the picture must change to count. Higher notices more, "
    "including shadows and rain.":
        "Wie stark sich eine Bildstelle ändern muss, damit sie zählt. Höher "
        "erkennt mehr — auch Schatten und Regen.",
    "Minimum area": "Mindestfläche",
    " ‰": " ‰",
    "How much of the watched area must change before it counts as motion. 20‰ "
    "is two percent of the picture — roughly a person at middle distance.":
        "Wie viel der überwachten Fläche sich ändern muss, damit es als "
        "Bewegung gilt. 20 ‰ sind zwei Prozent des Bildes — etwa eine Person "
        "auf mittlerer Entfernung.",
    "Raise an event on sound": "Bei Geräuschen ein Ereignis auslösen",
    "Needs a camera with a microphone. Opens another connection to the sub "
    "stream.":
        "Setzt ein Mikrofon in der Kamera voraus. Öffnet eine weitere "
        "Verbindung zum Substream.",
    "Sound above": "Geräusch lauter als",
    " dB": " dB",
    "-60 dB is close to silence, -20 dB a raised voice nearby.":
        "-60 dB ist nahezu still, -20 dB eine erhobene Stimme in der Nähe.",
    "Hold for": "Nachhalten",
    "Keeps the event up after the noise stops, so one bark is not reported "
    "four times.":
        "Hält das Ereignis nach dem Geräusch noch aufrecht, damit ein Bellen "
        "nicht viermal gemeldet wird.",

    # ── zone editor ──
    "%1 — motion zones": "%1 — Bewegungszonen",
    "no picture available": "kein Bild verfügbar",
    "Drag over the picture to choose what is watched. Darkened areas are "
    "ignored — useful for a road at the edge of view, a tree that moves in the "
    "wind, or a neighbour's doorway.":
        "Über das Bild ziehen, um den überwachten Bereich festzulegen. "
        "Abgedunkelte Flächen werden ignoriert — praktisch für eine Straße am "
        "Bildrand, einen Baum im Wind oder die Haustür des Nachbarn.",
    "Watch all": "Alles überwachen",
    "Ignore all": "Alles ignorieren",
    "Invert": "Umkehren",
    "Fetching a picture from %1…": "Hole ein Bild von %1…",
    "No picture: %1 — the zones can still be set.":
        "Kein Bild: %1 — die Zonen lassen sich trotzdem festlegen.",

    # ── recordings on the camera ──
    "Recordings on the &camera…": "Aufnahmen auf der &Kamera…",
    "Browse what is stored on the camera's own SD card.":
        "Zeigt, was auf der SD-Karte der Kamera liegt.",
    "Which camera": "Welche Kamera",
    "Show recordings from": "Aufnahmen anzeigen von",
    "%1 — recordings on the camera": "%1 — Aufnahmen auf der Kamera",
    "Search": "Suchen",
    "From": "Von",
    "to": "bis",
    "Main stream": "Hauptstream",
    "Sub stream": "Substream",
    "Start": "Beginn",
    "Length": "Dauer",
    "Size": "Größe",
    "File": "Datei",
    "Play": "Abspielen",
    "Download…": "Herunterladen…",
    "Pick a period and press Search. Recordings only exist if the camera has "
    "an SD card fitted.":
        "Zeitraum wählen und auf Suchen drücken. Aufnahmen gibt es nur, wenn "
        "eine SD-Karte in der Kamera steckt.",
    "Asking %1…": "Frage %1…",
    "Nothing found in that period. Either nothing was recorded, or the camera "
    "has no SD card.":
        "In diesem Zeitraum nichts gefunden. Entweder wurde nichts "
        "aufgezeichnet, oder die Kamera hat keine SD-Karte.",
    "No session with the camera — search first.":
        "Keine Sitzung mit der Kamera — bitte zuerst suchen.",
    "No player": "Kein Abspieler",
    "mpv was not found. The recording is at:\n\n%1":
        "mpv wurde nicht gefunden. Die Aufnahme liegt unter:\n\n%1",
    "Save recording": "Aufnahme speichern",
    "Cannot write to %1.": "Nach %1 lässt sich nicht schreiben.",
    "Saved to %1": "Gespeichert unter %1",
    "Download failed: %1": "Herunterladen fehlgeschlagen: %1",

    # ── errors from the camera ──
    "File format not recognised.": "Dateiformat nicht erkannt.",
    "Invalid input.": "Ungültige Eingabe.",
    "No free connections — the camera allows only a few sessions at a time.":
        "Keine freien Verbindungen — die Kamera erlaubt nur wenige Sitzungen "
        "gleichzeitig.",
    "Session expired.": "Sitzung abgelaufen.",
    "Wrong user name or password.": "Benutzername oder Passwort falsch.",
    "Timed out.": "Zeitüberschreitung.",
    "This firmware does not support that command.":
        "Diese Firmware kennt den Befehl nicht.",
    "Could not read the configuration.":
        "Die Konfiguration ließ sich nicht lesen.",
    "Could not verify the configuration.":
        "Die Konfiguration ließ sich nicht prüfen.",
    "Subsystem unavailable — typically no SD card fitted.":
        "Teilsystem nicht verfügbar — meist steckt keine SD-Karte.",
    "Not permitted — this model lacks the hardware.":
        "Nicht möglich — diesem Modell fehlt die Hardware dafür.",
    "Account invalid, log in again.":
        "Konto ungültig, bitte neu anmelden.",
    "User name already taken.": "Benutzername ist bereits vergeben.",
    "Maximum number of users reached.": "Maximale Benutzerzahl erreicht.",
    "Camera busy, try again shortly.":
        "Kamera beschäftigt, bitte gleich noch einmal versuchen.",
    "IP address conflict.": "IP-Adresskonflikt.",
    "Configuration test failed.": "Konfigurationstest fehlgeschlagen.",
    "FTP login failed.": "FTP-Anmeldung fehlgeschlagen.",
    "FTP could not create the directory.":
        "FTP konnte das Verzeichnis nicht anlegen.",
    "FTP upload failed.": "FTP-Übertragung fehlgeschlagen.",
    "FTP could not reach the server.": "FTP erreichte den Server nicht.",
    "Camera reported error %1.": "Die Kamera meldet Fehler %1.",
    "Cannot reach %1: %2": "%1 nicht erreichbar: %2",
    "Unexpected reply from %1.": "Unerwartete Antwort von %1.",
    "Login returned no token.": "Die Anmeldung lieferte kein Token.",
    "Snapshot failed.": "Standbild fehlgeschlagen.",
    "ONVIF subscription failed.": "ONVIF-Abonnement fehlgeschlagen.",
}

# Plural forms need one <numerusform> per German plural (singular, plural).
PLURALS: dict[str, list[str]] = {
    "%n camera(s) live": ["%n Kamera live", "%n Kameras live"],
    "Saved %n snapshot(s)": ["%n Standbild gespeichert",
                             "%n Standbilder gespeichert"],
    "Found %n device(s)…": ["%n Gerät gefunden…", "%n Geräte gefunden…"],
    "%n recording(s) found.": ["%n Aufnahme gefunden.", "%n Aufnahmen gefunden."],
}


def main() -> int:
    if not TS_FILE.exists():
        print(f"{TS_FILE} not found — run the update_translations target first.",
              file=sys.stderr)
        return 1

    text = TS_FILE.read_text(encoding="utf-8")
    filled = 0
    missing: list[str] = []

    def unescape(value: str) -> str:
        return (value.replace("&lt;", "<").replace("&gt;", ">")
                     .replace("&quot;", '"').replace("&apos;", "'")
                     .replace("&amp;", "&"))

    def replace(match: re.Match) -> str:
        nonlocal filled
        block = match.group(0)
        source_match = re.search(r"<source>(.*?)</source>", block, re.S)
        if not source_match:
            return block
        source = unescape(source_match.group(1))

        if source in PLURALS:
            forms = "".join(f"<numerusform>{escape(f)}</numerusform>"
                            for f in PLURALS[source])
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{forms}</translation>", block, flags=re.S)

        if source in GERMAN:
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{escape(GERMAN[source])}</translation>",
                          block, flags=re.S)

        missing.append(source)
        return block

    text = re.sub(r"<message[^>]*>.*?</message>", replace, text, flags=re.S)
    TS_FILE.write_text(text, encoding="utf-8")

    print(f"translated {filled} messages in {TS_FILE.name}")
    if missing:
        print(f"{len(missing)} still untranslated (English will be shown):")
        for m in missing[:20]:
            print(f"  · {m[:70]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
