#!/usr/bin/env python3
"""Fills the translation files from the tables in tools/i18n/.

The .ts files themselves are generated by lupdate (`cmake --build build
--target update_translations`). These tables only supply the translated text,
so regenerating the .ts after a code change does not mean retyping everything
— run lupdate, then run this.

Strings not listed are left untranslated, and Qt then falls back to the English
source, which is the right behaviour for a missing entry.

    python3 tools/fill_translations.py           # every language
    python3 tools/fill_translations.py de fr     # only these

Each tools/i18n/<code>.py provides:

    STRINGS  dict[str, str]        source     -> translation
    PLURALS  dict[str, list[str]]  source     -> one entry per plural form

The number of plural forms is decided by Qt from the language, not by us:
Japanese, Chinese and Turkish have one, most languages two, Russian three,
Arabic six. A table with the wrong count is reported rather than written.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
TABLES = Path(__file__).resolve().parent / "i18n"

# How many plural forms Qt expects, so a table can be checked before it is
# written into a .ts file where the mistake would be silent.
PLURAL_FORMS = {
    "ar": 6,
    "ru": 3,
    "ja": 1, "tr": 1, "zh_CN": 1,
}
DEFAULT_PLURAL_FORMS = 2


def unescape(value: str) -> str:
    return (value.replace("&lt;", "<").replace("&gt;", ">")
                 .replace("&quot;", '"').replace("&apos;", "'")
                 .replace("&amp;", "&"))


def load_table(code: str):
    path = TABLES / f"{code}.py"
    spec = importlib.util.spec_from_file_location(f"leolink_i18n_{code}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, "STRINGS", {}), getattr(module, "PLURALS", {})


def fill(code: str) -> tuple[int, list[str], list[str]]:
    """Returns (filled, still untranslated, complaints about the table)."""
    ts_file = ROOT / "translations" / f"leolink_{code}.ts"
    if not ts_file.exists():
        return 0, [], [f"{ts_file.name} not found — run lupdate first"]

    strings, plurals = load_table(code)
    forms_wanted = PLURAL_FORMS.get(code, DEFAULT_PLURAL_FORMS)
    complaints = [f"{source[:50]}: {len(forms)} plural form(s), "
                  f"{forms_wanted} expected"
                  for source, forms in plurals.items()
                  if len(forms) != forms_wanted]

    text = ts_file.read_text(encoding="utf-8")
    filled = 0
    missing: list[str] = []

    def replace(match: re.Match) -> str:
        nonlocal filled
        block = match.group(0)
        source_match = re.search(r"<source>(.*?)</source>", block, re.S)
        if not source_match:
            return block
        source = unescape(source_match.group(1))

        if source in plurals:
            forms = "".join(f"<numerusform>{escape(form)}</numerusform>"
                            for form in plurals[source])
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{forms}</translation>", block, flags=re.S)

        if source in strings:
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{escape(strings[source])}</translation>",
                          block, flags=re.S)

        missing.append(source)
        return block

    text = re.sub(r"<message[^>]*>.*?</message>", replace, text, flags=re.S)
    ts_file.write_text(text, encoding="utf-8")
    return filled, missing, complaints


def main() -> int:
    codes = sys.argv[1:] or sorted(p.stem for p in TABLES.glob("*.py")
                                   if p.stem != "__init__")
    if not codes:
        print(f"no tables in {TABLES}", file=sys.stderr)
        return 1

    failed = False
    for code in codes:
        filled, missing, complaints = fill(code)
        print(f"{code:>5}: translated {filled} message(s)"
              + (f", {len(missing)} left in English" if missing else ""))
        for complaint in complaints:
            print(f"       ! {complaint}", file=sys.stderr)
            failed = True
        for source in missing[:10]:
            print(f"       · {source[:70]}")
        if len(missing) > 10:
            print(f"       · … and {len(missing) - 10} more")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
