#!/usr/bin/env python3
"""Fills the German translation file with the strings below.

The .ts files themselves are generated by lupdate (`cmake --build build
--target update_translations`). This script only supplies the German text, so
regenerating the .ts after a code change does not mean retyping everything —
run lupdate, then run this.

Strings not listed here are left untranslated, and Qt then falls back to the
English source, which is the right behaviour for a missing entry.

    python3 tools/fill_german.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
TS_FILE = ROOT / "translations" / "leolink_de.ts"

# Source string → German. Plain text, no XML escaping: that is applied on write.
GERMAN: dict[str, str] = {
    # ── diagnostics and logging ──
    "Diagnostics": "Diagnose",
    "&Diagnostics…": "&Diagnose…",
    "What leolink and the cameras have been doing — and a report to attach to a "
    "bug report.":
        "Was leolink und die Kameras getan haben — und ein Bericht zum Anhängen "
        "an eine Fehlermeldung.",
    "Errors only": "Nur Fehler",
    "Warnings and errors": "Warnungen und Fehler",
    "Normal activity": "Normaler Betrieb",
    "Everything": "Alles",
    "All areas": "Alle Bereiche",
    "Search…": "Suchen…",
    "Show": "Zeigen",
    "Detailed logging": "Ausführliche Protokollierung",
    "Records every request to the camera, every decoder decision and every "
    "reconnect. Leave it off for everyday use — switch it on when something is "
    "wrong, reproduce the problem, then send the report.":
        "Zeichnet jede Anfrage an die Kamera auf, jede Decoder-Entscheidung und "
        "jeden Neuaufbau. Im Alltag ausgelassen — bei einem Problem einschalten, "
        "den Fehler erneut auslösen, dann den Bericht schicken.",
    "Records every request to the camera, every decoder decision and every "
    "reconnect, in ~/.local/share/leolink/leolink.log.":
        "Zeichnet jede Anfrage an die Kamera auf, jede Decoder-Entscheidung und "
        "jeden Neuaufbau, in ~/.local/share/leolink/leolink.log.",
    "Errors and warnings are always recorded. Detailed logging adds the "
    "conversation with the camera — switch it on when something is wrong, "
    "reproduce it, then send the report from Help ▸ Diagnostics. Passwords and "
    "tokens are removed before anything is written.":
        "Fehler und Warnungen werden immer aufgezeichnet. Die ausführliche "
        "Protokollierung ergänzt den Dialog mit der Kamera — bei einem Problem "
        "einschalten, den Fehler erneut auslösen, dann unter Hilfe ▸ Diagnose "
        "den Bericht schicken. Passwörter und Sitzungsschlüssel werden vorher "
        "entfernt.",
    "Open diagnostics…": "Diagnose öffnen…",
    "Open diagnostics": "Diagnose öffnen",
    "Follow new lines": "Neuen Zeilen folgen",
    "Copy report": "Bericht kopieren",
    "System details and the log, ready to paste into a bug report.":
        "Systemangaben und Protokoll, fertig zum Einfügen in eine Fehlermeldung.",
    "Report copied.": "Bericht kopiert.",
    "Save report…": "Bericht speichern…",
    "Save report": "Bericht speichern",
    "Text files (*.txt)": "Textdateien (*.txt)",
    "Could not write %1.": "%1 ließ sich nicht schreiben.",
    "Open log folder": "Protokollordner öffnen",
    "Passwords, session tokens and internet addresses are removed before "
    "anything is written, so this can be shared as it is. Addresses inside your "
    "own network are kept — they are usually the first clue.":
        "Passwörter, Sitzungsschlüssel und Internetadressen werden vor dem "
        "Schreiben entfernt; der Bericht kann also so weitergegeben werden. "
        "Adressen aus dem eigenen Netz bleiben stehen — sie sind meist der erste "
        "Anhaltspunkt.",
    "%1 of %2 lines": "%1 von %2 Zeilen",
    "Report a problem": "Ein Problem melden",
    "<b>Attach a diagnostics report</b>": "<b>Diagnosebericht anhängen</b>",
    "It records what your machine is, what the cameras answered and where "
    "things went wrong — with passwords and addresses already removed. Without "
    "it, most reports cannot be followed up.\n\nIf the problem is one you can "
    "trigger, switch on detailed logging in the diagnostics window first, make "
    "it happen again, then copy the report.":
        "Er hält fest, was für ein Rechner das ist, was die Kameras geantwortet "
        "haben und wo es schiefging — Passwörter und Adressen sind bereits "
        "entfernt. Ohne ihn lassen sich die meisten Meldungen nicht "
        "weiterverfolgen.\n\nLässt sich das Problem gezielt auslösen, vorher im "
        "Diagnosefenster die ausführliche Protokollierung einschalten, den "
        "Fehler erneut herbeiführen und dann den Bericht kopieren.",
    "Go to the issue tracker": "Zur Fehlerverwaltung",

    # ── log categories ──
    "Application": "Anwendung",
    "Camera API": "Kamera-Schnittstelle",
    "ONVIF events": "ONVIF-Ereignisse",
    "Event actions": "Ereignisaktionen",
    "Baichuan": "Baichuan",
    "User interface": "Benutzeroberfläche",
    "Qt": "Qt",

    # ── Wi-Fi scan ──
    "strong": "stark",
    "good": "gut",
    "fair": "mittel",
    "weak": "schwach",
    "unknown": "unbekannt",
    "%1 — %2 (%3/4)": "%1 — %2 (%3/4)",
    "Signal as the camera hears it: %1 of 4":
        "Signal, wie die Kamera es empfängt: %1 von 4",
    "Encryption: %1": "Verschlüsselung: %1",
    "Some names were heard from several access points — that is a mesh. The "
    "camera joins the name, not a particular node; the mesh decides which one "
    "it talks to and hands it over as needed. To find the best spot, move the "
    "camera and watch “Wi-Fi signal” above: that is the link it actually has.":
        "Einige Namen kamen von mehreren Zugangspunkten — das ist ein "
        "Mesh-Netz. Die Kamera verbindet sich mit dem Namen, nicht mit einem "
        "bestimmten Knoten; welcher das ist, handeln Kamera und Mesh unter sich "
        "aus und wechseln bei Bedarf. Für den besten Platz die Kamera "
        "verschieben und oben „WLAN-Signal“ beobachten: das ist die Verbindung, "
        "die sie tatsächlich hat.",

    # ── capability probe ──
    "What this camera supports": "Was diese Kamera unterstützt",
    "Reolink firmware differs enormously between models, and the only reliable "
    "way to know what a camera can do is to ask it. If something is missing "
    "from leolink that your camera clearly has, this list in a bug report is "
    "what makes it possible to add.":
        "Die Reolink-Firmware unterscheidet sich stark zwischen den Modellen; "
        "zuverlässig lässt sich nur durch Nachfragen klären, was eine Kamera "
        "kann. Fehlt in leolink etwas, das die Kamera offensichtlich beherrscht, "
        "macht genau diese Liste in einer Fehlermeldung das Nachrüsten möglich.",
    "Ask the camera": "Kamera fragen",
    "Copy the list": "Liste kopieren",
    "Copied.": "Kopiert.",
    "<b>Supported (%1):</b> %2<br><br><b>Not supported (%3):</b> %4":
        "<b>Unterstützt (%1):</b> %2<br><br><b>Nicht unterstützt (%3):</b> %4",

    # ── privacy areas ──
    "Privacy": "Privatsphäre",
    "Privacy areas…": "Privatzonen…",
    "Parts of the view the camera blanks before anything leaves it.":
        "Bildbereiche, die die Kamera schwärzt, bevor irgendetwas sie verlässt.",
    "Blanked in the camera itself, so the covered part is missing from every "
    "viewer and every recording — a neighbour's window, or a desk that should "
    "not be on film.":
        "In der Kamera selbst geschwärzt: der abgedeckte Teil fehlt in jedem "
        "Betrachter und jeder Aufnahme — das Fenster der Nachbarn etwa, oder ein "
        "Schreibtisch, der nicht auf Video gehört.",
    "%1 — privacy areas": "%1 — Privatzonen",
    "Drag out the parts of the view the camera should blank. It blacks them out "
    "before anything leaves the device, so they are missing from the live "
    "picture, from recordings and from every other client — including the "
    "manufacturer's app.":
        "Die Bereiche aufziehen, die die Kamera schwärzen soll. Sie schwärzt sie, "
        "bevor etwas das Gerät verlässt — sie fehlen also im Livebild, in "
        "Aufnahmen und in jedem anderen Programm, auch in der App des "
        "Herstellers.",
    "Remove the last": "Letzte entfernen",
    "Remove all": "Alle entfernen",
    "No picture: %1 — the areas can still be drawn.":
        "Kein Bild: %1 — die Bereiche lassen sich trotzdem einzeichnen.",
    "%1 of %2 areas": "%1 von %2 Bereichen",
    "nothing blanked": "nichts geschwärzt",

    # ── detection area and schedules ──
    "Detection area…": "Erfassungsbereich…",
    "Which parts of the picture the camera watches. Everything outside the area "
    "is ignored — a road at the edge of view, a tree in the wind, a neighbour's "
    "door.":
        "Welche Bildteile die Kamera überwacht. Alles außerhalb wird ignoriert — "
        "eine Straße am Bildrand, ein Baum im Wind, die Tür der Nachbarn.",
    "%1 — the camera's detection area": "%1 — Erfassungsbereich der Kamera",
    "Drag over the picture to choose what the camera watches. Darkened areas "
    "are ignored. This is the camera's own grid, %1 by %2, so it is finer than "
    "leolink's own.":
        "Über das Bild ziehen, um festzulegen, was die Kamera überwacht. "
        "Abgedunkelte Bereiche werden ignoriert. Das ist das Raster der Kamera "
        "selbst, %1 mal %2, also feiner als das von leolink.",
    "When to watch…": "Wann überwachen…",
    "Hours of the week the camera raises motion events at all.":
        "Stunden der Woche, in denen die Kamera überhaupt Bewegungsereignisse "
        "meldet.",
    "%1 — when to watch": "%1 — wann überwachen",
    "Hours in which the camera raises motion events. Outside them it still "
    "sees, but says nothing.":
        "Stunden, in denen die Kamera Bewegungsereignisse meldet. Außerhalb "
        "sieht sie weiterhin, sagt aber nichts.",
    "When to record…": "Wann aufnehmen…",
    "Hours of the week the camera records to its card by itself.":
        "Stunden der Woche, in denen die Kamera von sich aus auf ihre Karte "
        "aufnimmt.",
    "%1 — when to record": "%1 — wann aufnehmen",
    "Hours in which the camera records to its own card. This needs a card "
    "fitted; recording to this computer is set under Cameras → Events and works "
    "without one.":
        "Stunden, in denen die Kamera auf ihre eigene Karte aufnimmt. Dafür muss "
        "eine Karte eingesetzt sein; die Aufnahme auf diesen Rechner wird unter "
        "Kameras → Ereignisse eingestellt und kommt ohne Karte aus.",
    "Area, times and sensitivity": "Bereich, Zeiten und Empfindlichkeit",
    "To": "Bis",
    "Cameras allow a different sensitivity at different times of day, which is "
    "how you stop headlights at night triggering everything without going deaf "
    "during the day.":
        "Kameras erlauben je nach Tageszeit eine andere Empfindlichkeit — so "
        "lösen Scheinwerfer nachts nicht mehr alles aus, ohne dass die Kamera "
        "tagsüber blind wird.",

    # ── weekly schedule editor ──
    "All week": "Ganze Woche",
    "Never": "Nie",
    "Nights": "Nachts",
    "Working hours": "Arbeitszeit",
    "Weekends": "Wochenende",
    "22:00 to 06:00, every day.": "22:00 bis 06:00, täglich.",
    "08:00 to 17:00, Monday to Friday.": "08:00 bis 17:00, Montag bis Freitag.",
    "Nothing is selected — this will never run.":
        "Nichts ausgewählt — das läuft dann nie.",
    "Always on.": "Immer aktiv.",

    # ── mobile data ──
    "Mobile data": "Mobilfunk",
    "SIM card": "SIM-Karte",
    "PIN": "PIN",
    "Only needed if the card asks for one. Three wrong tries lock the card and "
    "it then needs a PUK, which only your operator has.":
        "Nur nötig, wenn die Karte danach fragt. Nach drei Fehlversuchen ist die "
        "Karte gesperrt und braucht eine PUK, die nur der Anbieter hat.",
    "Access point (APN)": "Zugangspunkt (APN)",
    "Authentication": "Anmeldeverfahren",
    "Use mobile data": "Mobilfunk verwenden",
    "Modem": "Modem",
    "Card": "Karte",
    "Type": "Art",
    "Signal": "Signal",
    "IMEI": "IMEI",
    "Card number": "Kartennummer",
    "Mobile connection": "Mobilfunkverbindung",
    "Data used": "Verbrauchtes Datenvolumen",
    "Monthly limit": "Monatsgrenze",
    "<b>Not tested on real hardware.</b> Nobody involved in leolink owns a "
    "camera with a modem, so this was written from the protocol alone. It "
    "cannot damage anything — a command the camera does not know is simply "
    "refused — but it may equally show nothing at all.\n\nIf your camera has a "
    "SIM, “What this camera supports” under Maintenance lists the commands its "
    "firmware actually has. That list, in a bug report, is what would let this "
    "be finished properly.":
        "<b>Nicht an echter Hardware getestet.</b> Niemand an leolink Beteiligter "
        "besitzt eine Kamera mit Modem; das hier entstand allein anhand des "
        "Protokolls. Kaputtgehen kann nichts — einen unbekannten Befehl weist "
        "die Kamera einfach ab — genauso gut kann aber gar nichts erscheinen."
        "\n\nHat Ihre Kamera eine SIM-Karte, listet „Was diese Kamera "
        "unterstützt“ unter Wartung die Befehle auf, die die Firmware "
        "tatsächlich kennt. Diese Liste in einer Fehlermeldung wäre das, was den "
        "Ausbau möglich macht.",

    # ── Baichuan transport ──
    "Baichuan (the camera's own protocol)":
        "Baichuan (das eigene Protokoll der Kamera)",
    "RTSP suits most cameras and is what to try first.\n\nHTTP-FLV needs only "
    "port 80, which helps where RTSP is blocked.\n\nBaichuan is what Reolink's "
    "own app speaks. It is the answer for cameras that keep RTSP switched off — "
    "battery models do — and it does not use the camera's small pool of web "
    "sessions. Video only: sound still comes over RTSP.":
        "RTSP passt zu den meisten Kameras und ist der erste Versuch."
        "\n\nHTTP-FLV braucht nur Port 80, was hilft, wo RTSP gesperrt ist."
        "\n\nBaichuan spricht Reolinks eigene App. Es ist die Antwort für "
        "Kameras, die RTSP abgeschaltet lassen — Akkumodelle tun das — und es "
        "belegt keine der wenigen Websitzungen der Kamera. Nur Video: der Ton "
        "kommt weiterhin über RTSP.",
    "connecting over Baichuan…": "verbinde über Baichuan…",
    "Cannot open a local port: %1": "Lokaler Port ließ sich nicht öffnen: %1",
    "Baichuan login failed: %1": "Baichuan-Anmeldung fehlgeschlagen: %1",
    "The camera refused to send video: %1":
        "Die Kamera verweigerte die Videoübertragung: %1",
    "The player did not connect.": "Der Player hat sich nicht verbunden.",
    "The camera stopped sending.": "Die Kamera sendet nicht mehr.",

    # ── firmware and read-out failures ──
    "The camera asks Reolink, not this computer — so it needs a way out to the "
    "internet of its own.":
        "Die Kamera fragt bei Reolink an, nicht dieser Rechner — sie braucht "
        "also einen eigenen Weg ins Internet.",
    "Part of the camera did not answer. Depending on what was asked, that means "
    "no SD card is fitted, or the camera has no way out to the internet.":
        "Ein Teil der Kamera hat nicht geantwortet. Je nachdem, wonach gefragt "
        "wurde, heißt das: keine SD-Karte eingesetzt, oder die Kamera kommt "
        "nicht ins Internet.",

    # ── maintenance ──
    "Factory reset is not offered here. It clears the network settings too, and "
    "a camera that has forgotten its Wi-Fi has to be taken down and reached by "
    "cable — use the camera's own web interface if you really want that.":
        "Das Zurücksetzen auf Werkseinstellungen gibt es hier nicht. Es löscht "
        "auch die Netzwerkeinstellungen, und eine Kamera, die ihr WLAN vergessen "
        "hat, muss abgenommen und per Kabel erreicht werden — wer das wirklich "
        "will, nimmt die Weboberfläche der Kamera.",
    "The camera has no free sessions. It allows only a handful at once, shared "
    "with the phone app and its web page. Close those, or wait a minute for the "
    "old ones to lapse.":
        "Die Kamera hat keine freien Sitzungen. Sie erlaubt nur eine Handvoll "
        "gleichzeitig, geteilt mit der Handy-App und ihrer Webseite. Diese "
        "schließen oder eine Minute warten, bis die alten ablaufen.",

    # ── menus ──
    "&File": "&Datei",
    "&View": "&Ansicht",
    "&Help": "&Hilfe",
    "&Cameras…": "&Kameras…",
    "&Save snapshots…": "&Standbilder speichern…",
    "&Event log…": "&Ereignisprotokoll…",
    "Open &recordings folder": "&Aufnahmeordner öffnen",
    "&Quit": "&Beenden",
    "&Full screen": "&Vollbild",
    "Show &menu bar": "&Menüleiste anzeigen",
    "Show &toolbar": "&Werkzeugleiste anzeigen",
    "Show status &bar": "&Statusleiste anzeigen",
    "Hide window &decoration": "Fenster&rahmen ausblenden",
    "&Online handbook": "&Online-Handbuch",
    "&Protocol notes": "&Protokollnotizen",
    "&Report a problem": "&Problem melden",
    "&About leolink": "Ü&ber leolink",
    "Main": "Haupt",

    # ── main window ──
    "Ready": "Bereit",
    "Grid view": "Gitteransicht",
    "No cameras configured": "Keine Kameras eingerichtet",
    "Nothing to capture": "Nichts aufzunehmen",
    "Save snapshots to": "Standbilder speichern unter",
    "Double-click to return to the grid": "Doppelklick führt zurück zum Gitter",
    "Cannot save": "Speichern nicht möglich",
    "Settings could not be written to %1.":
        "Die Einstellungen konnten nicht nach %1 geschrieben werden.",
    "Cannot create %1": "%1 kann nicht angelegt werden",
    "Recording %1": "Nimmt auf: %1",
    "Saved %1": "Gespeichert: %1",
    "Motion at %1": "Bewegung bei %1",
    "Motion detected": "Bewegung erkannt",
    "Could not run the motion command for %1":
        "Der Bewegungsbefehl für %1 ließ sich nicht ausführen",
    "leolink is still running": "leolink läuft weiter",
    "Cameras keep recording. Use the tray icon to come back.":
        "Die Kameras nehmen weiter auf. Über das Symbol im Systemabschnitt "
        "kommen Sie zurück.",
    "Show window": "Fenster anzeigen",
    "Cameras…": "Kameras…",
    "Quit": "Beenden",
    "Welcome to leolink": "Willkommen bei leolink",
    "<b>No cameras are configured yet.</b>":
        "<b>Es ist noch keine Kamera eingerichtet.</b>",
    "Add a camera with its address, user name and password. leolink talks to "
    "the camera directly on your network — no cloud account is involved."
    "<p>The handbook covers what each option does.":
        "Legen Sie eine Kamera mit Adresse, Benutzername und Passwort an. "
        "leolink spricht direkt im eigenen Netz mit der Kamera — ohne "
        "Cloud-Konto.<p>Was die einzelnen Optionen tun, steht im Handbuch.",
    "Add camera…": "Kamera hinzufügen…",
    "Open handbook": "Handbuch öffnen",
    "About leolink": "Über leolink",
    "<b>%1</b>": "<b>%1</b>",
    "<h3>leolink %1</h3><p>A native Linux client for Reolink cameras.</p>"
    "<p>Speaks the camera's own protocols directly: HTTP API, RTSP and ONVIF "
    "on the local network, and Reolink's P2P service when you want to reach a "
    "camera from elsewhere.</p>"
    "<p><a href=\"%2\">Handbook</a> · "
    "<a href=\"https://github.com/tombueng/leolink\">Source</a></p>"
    "<p>Not affiliated with or endorsed by Reolink.</p>":
        "<h3>leolink %1</h3><p>Ein nativer Linux-Client für Reolink-Kameras.</p>"
        "<p>Spricht direkt die Protokolle der Kamera: HTTP-API, RTSP und ONVIF "
        "im lokalen Netz, und Reolinks P2P-Dienst, wenn eine Kamera von "
        "auswärts erreichbar sein soll.</p>"
        "<p><a href=\"%2\">Handbuch</a> · "
        "<a href=\"https://github.com/tombueng/leolink\">Quelltext</a></p>"
        "<p>Nicht mit Reolink verbunden und nicht von Reolink unterstützt.</p>",
    "No cameras configured yet.\n\nUse “Cameras…” to add one.":
        "Noch keine Kamera eingerichtet.\n\nÜber „Kameras…“ eine anlegen.",

    # ── tile ──
    "connecting…": "verbinde…",
    "main stream": "Hauptstream",
    "sub stream": "Substream",
    "no host configured": "keine Adresse eingetragen",
    "cannot open stream": "Stream lässt sich nicht öffnen",
    "libmpv unavailable": "libmpv nicht verfügbar",
    "player init failed": "Wiedergabe ließ sich nicht starten",
    "MOTION": "BEWEGUNG",
    "Mute this camera": "Diese Kamera stummschalten",
    "Unmute this camera": "Stummschaltung aufheben",
    "Volume": "Lautstärke",
    "Camera settings": "Kameraeinstellungen",

    # ── settings: general ──
    "Settings": "Einstellungen",
    "Cameras": "Kameras",
    "Layout": "Anordnung",
    "Events": "Ereignisse",
    "Window": "Fenster",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Remove camera": "Kamera entfernen",
    "Remove “%1” from the list?": "„%1“ aus der Liste entfernen?",
    "New camera": "Neue Kamera",
    "Name": "Name",
    "Host": "Adresse",
    "User": "Benutzer",
    "Password": "Passwort",
    "Password command": "Passwortbefehl",
    "UID": "UID",
    "Stream": "Stream",
    "Transport": "Übertragung",
    "192.168.1.10 or camera.lan": "192.168.1.10 oder kamera.lan",
    "optional, for P2P access": "optional, für P2P-Zugriff",
    "optional: pass show reolink/hall": "optional: pass show reolink/flur",
    "If set, this command runs and its output is used as the password. Keeps "
    "the secret out of the configuration file.":
        "Ist das gesetzt, wird dieser Befehl ausgeführt und seine Ausgabe als "
        "Passwort verwendet. So steht das Geheimnis nicht in der "
        "Konfigurationsdatei.",
    "Sub stream (low bandwidth)": "Substream (wenig Bandbreite)",
    "Main stream (full resolution)": "Hauptstream (volle Auflösung)",
    "RTSP": "RTSP",
    "HTTP-FLV (lower latency)": "HTTP-FLV (geringere Latenz)",
    "Use HTTPS for the control API": "HTTPS für die Steuer-API verwenden",
    "Show this camera": "Diese Kamera anzeigen",
    "Test connection": "Verbindung testen",
    "Contacting %1…": "Kontaktiere %1…",
    "Enter a host first.": "Bitte zuerst eine Adresse eintragen.",
    "Incomplete camera": "Unvollständige Kamera",
    "“%1” has no host address.": "„%1“ hat keine Adresse.",
    "%1 — firmware %2, %3 channel(s)": "%1 — Firmware %2, %3 Kanäle",

    # ── settings: discovery ──
    "Scan network…": "Netzwerk durchsuchen…",
    "Ask the network which ONVIF cameras are present. This sends one multicast "
    "probe; devices that stay quiet are never contacted.":
        "Fragt im Netz nach vorhandenen ONVIF-Kameras. Dabei geht eine einzige "
        "Multicast-Anfrage hinaus; Geräte, die schweigen, werden nicht "
        "kontaktiert.",
    "Looking for cameras…": "Suche Kameras…",
    "Stop": "Abbrechen",
    "Cameras found": "Kameras gefunden",
    "Add which one?": "Welche hinzufügen?",
    "No cameras found": "Keine Kameras gefunden",
    "No ONVIF device answered.\n\nCameras only reply if ONVIF is switched on, "
    "and the probe does not cross routers or most VPNs. You can still add a "
    "camera by typing its address.":
        "Kein ONVIF-Gerät hat geantwortet.\n\nKameras antworten nur, wenn "
        "ONVIF eingeschaltet ist; die Anfrage überquert weder Router noch die "
        "meisten VPNs. Sie können die Kamera weiterhin von Hand über ihre "
        "Adresse eintragen.",
    "unnamed device": "unbenanntes Gerät",
    " (Reolink)": " (Reolink)",
    "Cannot open a UDP socket for discovery.":
        "Für die Suche ließ sich kein UDP-Socket öffnen.",

    # ── settings: layout ──
    "Grid size": "Gittergröße",
    "Columns": "Spalten",
    "Rows": "Zeilen",
    "Column": "Spalte",
    "Row": "Zeile",
    "Row span": "Zeilen überspannen",
    "Column span": "Spalten überspannen",
    "automatic": "automatisch",
    "Position of the selected camera": "Position der gewählten Kamera",
    "Leave row and column on “automatic” to let cameras fill the grid in "
    "order. Spans let one camera cover several cells.":
        "Bleiben Zeile und Spalte auf „automatisch“, füllen die Kameras das "
        "Gitter der Reihe nach. Über die Überspannung belegt eine Kamera "
        "mehrere Felder.",

    # ── settings: events ──
    "Watch cameras for motion (ONVIF push)":
        "Kameras auf Bewegung überwachen (ONVIF-Push)",
    "The camera reports motion when it happens, rather than leolink asking "
    "once a second.":
        "Die Kamera meldet Bewegung, sobald sie auftritt — leolink muss nicht "
        "im Sekundentakt nachfragen.",
    "Run command": "Befehl ausführen",
    "notify-send \"Motion at %n\"": "notify-send \"Bewegung bei %n\"",
    "Runs when this camera reports motion.\n"
    "%n camera name · %h host · %t timestamp · %f recording file":
        "Wird ausgeführt, wenn diese Kamera Bewegung meldet.\n"
        "%n Kameraname · %h Adresse · %t Zeitstempel · %f Aufnahmedatei",
    "Record while motion lasts": "Während der Bewegung aufnehmen",
    "Records on this computer from the live stream, so it works even when the "
    "camera has no SD card fitted.":
        "Nimmt auf diesem Rechner aus dem Livestream auf — funktioniert also "
        "auch ohne SD-Karte in der Kamera.",
    "Keep recording after": "Nachlauf der Aufnahme",
    " s": " s",
    "Selected camera": "Gewählte Kamera",
    "All cameras": "Alle Kameras",
    "Recordings folder": "Aufnahmeordner",
    "Browse…": "Durchsuchen…",
    "Recordings are written as Matroska without re-encoding: the picture keeps "
    "the camera's original quality and the CPU stays nearly idle.":
        "Aufnahmen werden als Matroska ohne Neukodierung geschrieben: das Bild "
        "behält die Originalqualität der Kamera, und der Prozessor bleibt "
        "nahezu unbelastet.",

    # ── settings: window ──
    "Appearance": "Darstellung",
    "Show menu bar": "Menüleiste anzeigen",
    "Show toolbar": "Werkzeugleiste anzeigen",
    "Show status bar": "Statusleiste anzeigen",
    "Hide window decoration": "Fensterrahmen ausblenden",
    "Ctrl+M toggles this at any time.": "Strg+M schaltet das jederzeit um.",
    "For wall displays. Ctrl+Shift+D toggles it.":
        "Für Wanddisplays. Strg+Umschalt+D schaltet um.",
    "Notification area": "Systemabschnitt",
    "Show an icon in the notification area":
        "Symbol im Systemabschnitt anzeigen",
    "Closing the window hides it instead of quitting":
        "Schließen blendet das Fenster aus, statt zu beenden",
    "Minimising hides the window to the tray":
        "Minimieren blendet das Fenster in den Systemabschnitt aus",
    "On motion": "Bei Bewegung",
    "Bring the window up when motion is detected":
        "Fenster bei erkannter Bewegung hervorholen",
    "Come back as": "Zurückkommen als",
    "Previous size": "Vorherige Größe",
    "Full screen": "Vollbild",
    "Language": "Sprache",
    "System language": "Systemsprache",
    "Takes effect after restarting leolink.":
        "Wird nach einem Neustart von leolink wirksam.",
    "Menu bar hidden": "Menüleiste ausgeblendet",
    "With both the menu bar and the toolbar hidden, press Ctrl+M to bring the "
    "menu back.":
        "Sind Menü- und Werkzeugleiste beide ausgeblendet, holt Strg+M das "
        "Menü zurück.",

    # ── event log ──
    "Event log": "Ereignisprotokoll",
    "Camera:": "Kamera:",
    "Show:": "Anzeigen:",
    "All events": "Alle Ereignisse",
    "Motion": "Bewegung",
    "With recording": "Mit Aufnahme",
    "Refresh": "Aktualisieren",
    "When": "Wann",
    "Camera": "Kamera",
    "Event": "Ereignis",
    "Media": "Medien",
    "video": "Video",
    "image": "Bild",
    " + image": " + Bild",
    "no preview": "keine Vorschau",
    "recording only": "nur Aufnahme",
    "no events recorded yet": "noch keine Ereignisse aufgezeichnet",
    "Recording: %1%2": "Aufnahme: %1%2",
    " (file missing)": " (Datei fehlt)",
    "Image: %1": "Bild: %1",
    "Open recording": "Aufnahme öffnen",
    "Open image": "Bild öffnen",
    "Nothing to open": "Nichts zu öffnen",
    "The file for this event is no longer there.":
        "Die Datei zu diesem Ereignis ist nicht mehr vorhanden.",
    "Clear log…": "Protokoll leeren…",
    "Clear event log": "Ereignisprotokoll leeren",
    "Delete the whole event history?\n\nRecorded videos and images stay on "
    "disk — only the log is cleared.":
        "Den gesamten Ereignisverlauf löschen?\n\nAufgezeichnete Videos und "
        "Bilder bleiben erhalten — nur das Protokoll wird geleert.",

    # ── event actions ──
    "Command": "Befehl",
    "could not be started": "ließ sich nicht starten",
    "Webhook": "Webhook",
    "invalid URL": "ungültige Adresse",
    "Webhook → %1": "Webhook → %1",
    "%1 failed: %2": "%1 fehlgeschlagen: %2",
    "Event log…": "Ereignisprotokoll…",
    "MQTT broker or topic not set.":
        "MQTT-Broker oder Topic nicht gesetzt.",
    "MQTT broker did not respond.": "Der MQTT-Broker hat nicht geantwortet.",
    "MQTT: %1": "MQTT: %1",
    "MQTT: unexpected reply from the broker.":
        "MQTT: unerwartete Antwort des Brokers.",
    "MQTT refused the connection: %1":
        "MQTT hat die Verbindung abgelehnt: %1",

    # ── decoding ──
    "Video": "Video",
    "Decoding": "Dekodierung",
    "Hardware, fastest": "Hardware, am schnellsten",
    "Hardware, with frame copy": "Hardware, mit Bildkopie",
    "Software only": "Nur Software",
    "Hardware decoding keeps the processor free and is the right choice for "
    "main-stream resolutions.\n\n"
    "If the picture shows green blocks or stalls, pick “with frame copy”: it "
    "still decodes on the GPU but copies each frame to main memory, which some "
    "drivers need when the video sits inside another window.":
        "Hardware-Dekodierung hält den Prozessor frei und ist bei "
        "Hauptstream-Auflösungen die richtige Wahl.\n\n"
        "Zeigt das Bild grüne Flächen oder stockt es, wählen Sie „mit "
        "Bildkopie“: dekodiert weiterhin auf der GPU, kopiert aber jedes Bild "
        "in den Hauptspeicher — das brauchen manche Treiber, wenn das Video in "
        "einem anderen Fenster eingebettet ist.",
    "Favour low latency over smoothness":
        "Niedrige Latenz wichtiger als flüssige Wiedergabe",
    "Keeps buffering to a minimum. Turn this off if a high-bitrate stream "
    "stutters over a busy network.":
        "Hält die Pufferung minimal. Bei ruckelnden Streams mit hoher Bitrate "
        "in einem ausgelasteten Netz besser abschalten.",

    # ── frameless hint ──
    "Drag the strip under a camera to move the window. Ctrl+Shift+D brings the "
    "frame back, Ctrl+M the menu.":
        "Zum Verschieben die Leiste unter einer Kamera ziehen. Strg+Umschalt+D "
        "holt den Rahmen zurück, Strg+M das Menü.",

    # ── camera settings dialog ──
    "%1 — camera settings": "%1 — Kameraeinstellungen",
    "Reading settings from %1…": "Lese Einstellungen von %1…",
    "Apply to camera": "Auf Kamera anwenden",
    "Main stream": "Hauptstream",
    "Sub stream": "Substream",
    "Resolution": "Auflösung",
    "Frame rate": "Bildrate",
    "Bit rate (kbit/s)": "Bitrate (kbit/s)",
    "H.264 profile": "H.264-Profil",
    "Higher means better picture and more network traffic. The camera only "
    "offers the rates it can actually sustain.":
        "Höher heißt besseres Bild und mehr Netzlast. Die Kamera bietet nur "
        "die Raten an, die sie auch halten kann.",
    "These change the camera itself, so every client sees the result. The "
    "choices come from the camera and differ per model.":
        "Das verändert die Kamera selbst — jeder Client sieht das Ergebnis. "
        "Die Auswahl kommt von der Kamera und unterscheidet sich je Modell.",
    "Picture": "Bild",
    "Brightness": "Helligkeit",
    "Contrast": "Kontrast",
    "Saturation": "Sättigung",
    "Sharpness": "Schärfe",
    "Hue": "Farbton",
    "Ready.": "Bereit.",
    "Writing to the camera…": "Schreibe auf die Kamera…",
    "Nothing to write.": "Nichts zu schreiben.",
    "Saved. Changing the encoder restarts the stream, so the picture may drop "
    "out for a moment.":
        "Gespeichert. Eine Encoder-Änderung startet den Stream neu, das Bild "
        "kann daher kurz aussetzen.",

    # ── recording ──
    "&Record all cameras": "Alle Kameras &aufnehmen",
    "Record this camera": "Diese Kamera aufnehmen",
    "Stop recording": "Aufnahme beenden",
    "Recording all cameras": "Nehme alle Kameras auf",
    "Recording stopped": "Aufnahme beendet",
    "Recording started": "Aufnahme gestartet",
    "Could not start recording %1":
        "Aufnahme von %1 ließ sich nicht starten",

    # ── recorder ──
    "%1: %2": "%1: %2",
    "ffmpeg is not installed, so recording is unavailable.":
        "ffmpeg ist nicht installiert, Aufnahmen sind daher nicht möglich.",
    "No stream address for %1.": "Keine Stream-Adresse für %1.",
    "Recording failed: %1": "Aufnahme fehlgeschlagen: %1",
    "Recording produced no data (ffmpeg exit %1).":
        "Die Aufnahme enthält keine Daten (ffmpeg-Rückgabewert %1).",
    "Could not start ffmpeg.": "ffmpeg ließ sich nicht starten.",

    # ── custom source ──
    "Custom URL": "Eigene Adresse",
    "Any address libmpv can open. Use this for cameras from other makers, an "
    "NVR stream, or a local file.":
        "Jede Adresse, die libmpv öffnen kann — für Kameras anderer Hersteller, "
        "einen NVR-Stream oder eine lokale Datei.",

    # ── detectors ──
    "ffmpeg is not installed, so motion detection is unavailable.":
        "ffmpeg ist nicht installiert, Bewegungserkennung daher nicht möglich.",
    "ffmpeg is not installed, so sound detection is unavailable.":
        "ffmpeg ist nicht installiert, Geräuscherkennung daher nicht möglich.",
    "Motion detection stopped: %1": "Bewegungserkennung beendet: %1",
    "Sound detection stopped: %1": "Geräuscherkennung beendet: %1",
    "Could not start ffmpeg for motion detection.":
        "ffmpeg für die Bewegungserkennung ließ sich nicht starten.",
    "Could not start ffmpeg for sound detection.":
        "ffmpeg für die Geräuscherkennung ließ sich nicht starten.",
    "Sound detected": "Geräusch erkannt",
    "%1 at %2": "%1 bei %2",
    "Detection": "Erkennung",
    "Motion comes from": "Bewegung meldet",
    "The camera reports it (ONVIF)": "Die Kamera selbst (ONVIF)",
    "leolink watches the picture": "leolink beobachtet das Bild",
    "Either of the two": "Beides",
    "Do not watch": "Nicht überwachen",
    "Cameras that report motion themselves cost nothing to watch.\n\n"
    "Analysing the picture here works with any camera, including ones that "
    "report nothing, but opens a second connection to the sub stream for each.":
        "Kameras, die Bewegung selbst melden, kosten nichts.\n\n"
        "Die Bildanalyse hier funktioniert mit jeder Kamera, auch mit solchen, "
        "die nichts melden — öffnet aber je Kamera eine zweite Verbindung zum "
        "Substream.",
    "Motion zones…": "Bewegungszonen…",
    "Choose which parts of the picture are watched. Only applies when leolink "
    "analyses the picture itself.":
        "Legt fest, welche Bildbereiche überwacht werden. Gilt nur, wenn "
        "leolink das Bild selbst analysiert.",
    "Sensitivity": "Empfindlichkeit",
    "How much a spot in the picture must change to count. Higher notices more, "
    "including shadows and rain.":
        "Wie stark sich eine Bildstelle ändern muss, damit sie zählt. Höher "
        "erkennt mehr — auch Schatten und Regen.",
    "Minimum area": "Mindestfläche",
    " ‰": " ‰",
    "How much of the watched area must change before it counts as motion. 20‰ "
    "is two percent of the picture — roughly a person at middle distance.":
        "Wie viel der überwachten Fläche sich ändern muss, damit es als "
        "Bewegung gilt. 20 ‰ sind zwei Prozent des Bildes — etwa eine Person "
        "auf mittlerer Entfernung.",
    "Raise an event on sound": "Bei Geräuschen ein Ereignis auslösen",
    "Needs a camera with a microphone. Opens another connection to the sub "
    "stream.":
        "Setzt ein Mikrofon in der Kamera voraus. Öffnet eine weitere "
        "Verbindung zum Substream.",
    "Sound above": "Geräusch lauter als",
    " dB": " dB",
    "-60 dB is close to silence, -20 dB a raised voice nearby.":
        "-60 dB ist nahezu still, -20 dB eine erhobene Stimme in der Nähe.",
    "Hold for": "Nachhalten",
    "Keeps the event up after the noise stops, so one bark is not reported "
    "four times.":
        "Hält das Ereignis nach dem Geräusch noch aufrecht, damit ein Bellen "
        "nicht viermal gemeldet wird.",

    # ── zone editor ──
    "%1 — motion zones": "%1 — Bewegungszonen",
    "no picture available": "kein Bild verfügbar",
    "Drag over the picture to choose what is watched. Darkened areas are "
    "ignored — useful for a road at the edge of view, a tree that moves in the "
    "wind, or a neighbour's doorway.":
        "Über das Bild ziehen, um den überwachten Bereich festzulegen. "
        "Abgedunkelte Flächen werden ignoriert — praktisch für eine Straße am "
        "Bildrand, einen Baum im Wind oder die Haustür des Nachbarn.",
    "Watch all": "Alles überwachen",
    "Ignore all": "Alles ignorieren",
    "Invert": "Umkehren",
    "Fetching a picture from %1…": "Hole ein Bild von %1…",
    "No picture: %1 — the zones can still be set.":
        "Kein Bild: %1 — die Zonen lassen sich trotzdem festlegen.",

    # ── recordings on the camera ──
    "Recordings on the &camera…": "Aufnahmen auf der &Kamera…",
    "Browse what is stored on the camera's own SD card.":
        "Zeigt, was auf der SD-Karte der Kamera liegt.",
    "Which camera": "Welche Kamera",
    "Show recordings from": "Aufnahmen anzeigen von",
    "%1 — recordings on the camera": "%1 — Aufnahmen auf der Kamera",
    "Search": "Suchen",
    "From": "Von",
    "to": "bis",
    "Main stream": "Hauptstream",
    "Sub stream": "Substream",
    "Start": "Beginn",
    "Length": "Dauer",
    "Size": "Größe",
    "File": "Datei",
    "Play": "Abspielen",
    "Download…": "Herunterladen…",
    "Pick a period and press Search. Recordings only exist if the camera has "
    "an SD card fitted.":
        "Zeitraum wählen und auf Suchen drücken. Aufnahmen gibt es nur, wenn "
        "eine SD-Karte in der Kamera steckt.",
    "Asking %1…": "Frage %1…",
    "Nothing found in that period. Either nothing was recorded, or the camera "
    "has no SD card.":
        "In diesem Zeitraum nichts gefunden. Entweder wurde nichts "
        "aufgezeichnet, oder die Kamera hat keine SD-Karte.",
    "No session with the camera — search first.":
        "Keine Sitzung mit der Kamera — bitte zuerst suchen.",
    "No player": "Kein Abspieler",
    "mpv was not found. The recording is at:\n\n%1":
        "mpv wurde nicht gefunden. Die Aufnahme liegt unter:\n\n%1",
    "Save recording": "Aufnahme speichern",
    "Cannot write to %1.": "Nach %1 lässt sich nicht schreiben.",
    "Saved to %1": "Gespeichert unter %1",
    "Download failed: %1": "Herunterladen fehlgeschlagen: %1",

    # ── maintenance ──
    "Maintenance": "Wartung",
    "Restart": "Neustart",
    "Restart the camera": "Kamera neu starten",
    "The camera goes off the network for a minute or so and comes back on its "
    "own. Recordings on its SD card are not affected, and settings are kept.\n\n"
    "Worth trying when a camera has stopped answering, is refusing new "
    "connections, or has drifted out of step after a firmware update.":
        "Die Kamera ist etwa eine Minute lang nicht erreichbar und meldet sich "
        "danach von selbst zurück. Aufnahmen auf der SD-Karte und Einstellungen "
        "bleiben erhalten.\n\n"
        "Einen Versuch wert, wenn eine Kamera nicht mehr antwortet, keine neuen "
        "Verbindungen annimmt oder sich nach einem Firmware-Update seltsam "
        "verhält.",
    "<b>Restart %1?</b>": "<b>%1 neu starten?</b>",
    "The picture will be gone for about a minute. Anything being recorded right "
    "now will stop.":
        "Das Bild ist etwa eine Minute lang weg. Eine gerade laufende Aufnahme "
        "wird beendet.",
    "Asking %1 to restart…": "Fordere Neustart von %1 an…",
    "Restarting. The camera will be back in about a minute.":
        "Startet neu. Die Kamera ist in etwa einer Minute wieder da.",
    "Factory reset and formatting the SD card are not offered here. Both are "
    "irreversible and are better done in the camera's own web interface, where "
    "the warnings are the manufacturer's.":
        "Werksreset und das Formatieren der SD-Karte gibt es hier bewusst "
        "nicht. Beides ist unumkehrbar und gehört in die Weboberfläche der "
        "Kamera, wo die Warnungen vom Hersteller stammen.",

    # ── network tab and signal ──
    "Network": "Netzwerk",
    "Connection": "Verbindung",
    "Reading…": "Lese…",
    "Wi-Fi signal": "WLAN-Signal",
    "Wi-Fi signal unknown": "WLAN-Signal unbekannt",
    "Wi-Fi signal %1 of %2": "WLAN-Signal %1 von %2",
    "Link": "Anbindung",
    "Address": "Adresse",
    "Netmask": "Netzmaske",
    "Gateway": "Gateway",
    "MAC": "MAC",
    "DNS": "DNS",
    "Network name": "Netzwerkname",
    "Ports": "Ports",
    "The camera reported nothing.": "Die Kamera hat nichts gemeldet.",
    "Shown for reference. Addresses, Wi-Fi credentials and ports are changed "
    "in the camera's own web interface — a mistake here would put the camera "
    "out of reach.":
        "Nur zur Information. Adressen, WLAN-Zugangsdaten und Ports werden in "
        "der Weboberfläche der Kamera geändert — ein Fehler hier würde die "
        "Kamera unerreichbar machen.",

    # ── decoding, reworded ──
    "Hardware, with frame copy (recommended)":
        "Hardware, mit Bildkopie (empfohlen)",
    "Hardware, zero copy (fastest)": "Hardware, ohne Kopie (am schnellsten)",
    "All three decode on the graphics card where it can.\n\n"
    "“With frame copy” hands each frame through main memory. It is a few "
    "percent slower and it is the default, because the zero-copy path produces "
    "green blocks or a frozen picture on several drivers when the video sits "
    "inside another window.\n\n"
    "Try “zero copy” if you want the last few percent; go back if the picture "
    "breaks up.":
        "Alle drei dekodieren auf der Grafikkarte, soweit möglich.\n\n"
        "„Mit Bildkopie“ reicht jedes Bild durch den Hauptspeicher. Das ist "
        "wenige Prozent langsamer und die Vorgabe, weil der Weg ohne Kopie auf "
        "mehreren Treibern grüne Flächen oder ein stehendes Bild erzeugt, wenn "
        "das Video in einem anderen Fenster eingebettet ist.\n\n"
        "„Ohne Kopie“ holt die letzten Prozent heraus; bei Bildfehlern wieder "
        "zurückstellen.",

    # ── camera sections (generated forms) ──
    "This camera does not offer these settings.":
        "Diese Kamera bietet diese Einstellungen nicht.",
    "Exposure and orientation": "Belichtung und Ausrichtung",
    "Day / night": "Tag / Nacht",
    "Automatic": "Automatisch",
    "Always colour": "Immer Farbe",
    "Always black and white": "Immer Schwarzweiß",
    "“Auto” switches to infrared as the light goes. Forcing colour at night "
    "gives a picture too dark to use; forcing black and white by day loses "
    "colour for nothing.":
        "„Automatisch“ schaltet bei nachlassendem Licht auf Infrarot um. "
        "Erzwungene Farbe nachts ergibt ein zu dunkles Bild; erzwungenes "
        "Schwarzweiß tagsüber verschenkt die Farbe ohne Gegenwert.",
    "Anti-flicker": "Flimmerfilter",
    "Match your mains frequency — 50 Hz in Europe — or indoor lighting will "
    "beat against the shutter and the picture will pulse.":
        "Auf die Netzfrequenz stellen — in Europa 50 Hz — sonst schwebt "
        "Kunstlicht gegen den Verschluss und das Bild pulsiert.",
    "Exposure": "Belichtung",
    "Mirror": "Spiegeln",
    "Flip": "Kippen",
    "For a camera mounted upside down.": "Für über Kopf montierte Kameras.",
    "Backlight compensation": "Gegenlichtausgleich",
    "Helps when the subject stands against a bright window or sky.":
        "Hilft, wenn das Motiv vor einem hellen Fenster oder Himmel steht.",
    "Noise reduction": "Rauschunterdrückung",
    "Cleans up a dark picture, at the cost of smearing anything that moves.":
        "Beruhigt ein dunkles Bild, verschmiert dafür alles, was sich bewegt.",
    "Rotation": "Drehung",
    "Dynamic contrast": "Dynamischer Kontrast",
    "Infrared illumination": "Infrarotbeleuchtung",
    "Infrared lamps": "Infrarotlampen",
    "Always on": "Immer an",
    "Always off": "Immer aus",
    "“Auto” turns them on when it gets dark. Switch them off if the camera "
    "looks through glass — the reflection blinds it.":
        "„Automatisch“ schaltet sie bei Dunkelheit ein. Bei Blick durch eine "
        "Scheibe abschalten — die Reflexion blendet die Kamera.",

    # ── overlay ──
    "Overlay": "Einblendung",
    "On-screen text": "Text im Bild",
    "Background": "Hintergrund",
    "Draws a box behind the text so it stays readable over a bright scene.":
        "Legt einen Kasten hinter den Text, damit er auch vor hellem "
        "Hintergrund lesbar bleibt.",
    "Watermark": "Wasserzeichen",
    "Embeds a mark in the recording itself.":
        "Bettet eine Markierung in die Aufnahme selbst ein.",
    "The camera burns this into the picture, so it appears in every recording "
    "and every client — not only here.":
        "Die Kamera brennt das ins Bild — es erscheint in jeder Aufnahme und "
        "in jedem Client, nicht nur hier.",

    # ── detection in the camera ──
    "Motion detection in the camera": "Bewegungserkennung in der Kamera",
    "Switched on": "Eingeschaltet",
    "Higher notices more, including shadows and headlights.":
        "Höher erkennt mehr — auch Schatten und Scheinwerfer.",
    "This is the camera's own detection, the one it reports over ONVIF. "
    "leolink's own analysis of the picture is set separately, under "
    "Cameras → Events.":
        "Das ist die Erkennung der Kamera selbst, die sie über ONVIF meldet. "
        "leolinks eigene Bildanalyse wird getrennt eingestellt, unter "
        "Kameras → Ereignisse.",

    # ── recording on the camera ──
    "Recording": "Aufnahme",
    "Recording to the camera's card": "Aufnahme auf die Karte der Kamera",
    "Overwrite when full": "Bei vollem Speicher überschreiben",
    "Off means recording simply stops once the card fills up.":
        "Aus bedeutet, dass die Aufnahme bei voller Karte einfach endet.",
    "Record before the event": "Vorlauf aufzeichnen",
    "Keeps the seconds leading up to a trigger, which is usually the "
    "interesting part.":
        "Behält die Sekunden vor dem Auslöser — meist der interessante Teil.",
    "Keep recording after": "Nachlauf aufzeichnen",
    "File length": "Dateilänge",
    "These govern what the camera writes to its own SD card. Recording to this "
    "computer is set under Cameras → Events and needs no card.":
        "Das steuert, was die Kamera auf ihre eigene SD-Karte schreibt. Die "
        "Aufnahme auf diesen Rechner wird unter Kameras → Ereignisse "
        "eingestellt und braucht keine Karte.",

    # ── alerts from the camera ──
    "Alerts": "Benachrichtigungen",
    "E-mail": "E-Mail",
    "FTP": "FTP",
    "FTP upload": "FTP-Upload",
    "Push notification": "Push-Nachricht",
    "Server": "Server",
    "Port": "Port",
    "Send to": "Senden an",
    "Encrypted": "Verschlüsselt",
    "Not more often than": "Höchstens alle",
    "Attach": "Anhang",
    "Directory": "Verzeichnis",
    "Mode": "Modus",
    "Schedule": "Zeitplan",
    "Sent by the camera itself, so they keep working when this computer is "
    "switched off. leolink's own reactions — commands, webhooks, MQTT — are "
    "under Cameras → Events.":
        "Verschickt die Kamera selbst, sie funktionieren also auch bei "
        "ausgeschaltetem Rechner. leolinks eigene Reaktionen — Befehle, "
        "Webhooks, MQTT — stehen unter Kameras → Ereignisse.",

    # ── time ──
    "Time": "Zeit",
    "Time server": "Zeitserver",
    "Synchronise the clock": "Uhr abgleichen",
    "Every": "Alle",
    "Scheduled restart": "Geplanter Neustart",
    "Restart regularly": "Regelmäßig neu starten",
    "Some cameras become unreliable after weeks of uptime; a weekly restart is "
    "a cheap cure.":
        "Manche Kameras werden nach Wochen Laufzeit unzuverlässig; ein "
        "wöchentlicher Neustart ist ein billiges Gegenmittel.",
    "Day": "Tag",
    "Hour": "Stunde",
    "Minute": "Minute",
    "A camera with the wrong clock stamps its recordings wrongly, which is "
    "worth more than it sounds when you need to find one.":
        "Eine Kamera mit falscher Uhr stempelt ihre Aufnahmen falsch — das "
        "wiegt schwerer, als es klingt, wenn man eine davon sucht.",

    # ── wifi setup ──
    "Wi-Fi": "WLAN",
    "Network": "Netzwerk",
    "Scan": "Suchen",
    "Join network": "Netzwerk beitreten",
    "scanning…": "suche…",
    "The camera is scanning for networks…": "Die Kamera sucht nach Netzwerken…",
    "The camera scans, not this computer — what it can reach is what counts. "
    "The password is tried before it is saved, so a typo is refused rather "
    "than leaving the camera on no network at all.":
        "Es sucht die Kamera, nicht dieser Rechner — entscheidend ist, was sie "
        "erreicht. Das Passwort wird vor dem Speichern geprüft; ein Tippfehler "
        "wird also abgewiesen, statt die Kamera ohne Netz zurückzulassen.",
    "Change the camera's network": "Netzwerk der Kamera wechseln",
    "<b>Move %1 to “%2”?</b>": "<b>%1 in „%2“ umziehen?</b>",
    "The camera tests the password first and refuses if it is wrong, so this "
    "is safer than it sounds.\n\n"
    "It will still disappear for a minute while it reconnects, and if the new "
    "network hands out a different address you will have to update it here "
    "afterwards.":
        "Die Kamera prüft das Passwort vorab und lehnt ein falsches ab — das "
        "ist also ungefährlicher, als es klingt.\n\n"
        "Sie verschwindet trotzdem für eine Minute, und wenn das neue Netz "
        "eine andere Adresse vergibt, muss sie hier nachgetragen werden.",
    "Join": "Beitreten",
    "Testing the password on the camera…": "Prüfe das Passwort auf der Kamera…",
    "Saved. The camera is reconnecting and will be back shortly.":
        "Gespeichert. Die Kamera verbindet sich neu und ist gleich wieder da.",
    "The camera could not join that network: %1":
        "Die Kamera konnte diesem Netzwerk nicht beitreten: %1",
    "Addresses and ports are read here but changed in the camera's own web "
    "interface. Getting one wrong takes the camera off the network entirely, "
    "and the only way back is the reset pin — a warning dialog is no "
    "substitute for the manufacturer's own screen there.":
        "Adressen und Ports werden hier nur gelesen und in der Weboberfläche "
        "der Kamera geändert. Ein Fehler nimmt die Kamera komplett vom Netz, "
        "und der einzige Weg zurück ist die Reset-Nadel — dafür ist ein "
        "Warnhinweis kein Ersatz für den Bildschirm des Herstellers.",

    # ── stream status ──
    "%1 fps": "%1 fps",
    "%1 Mbit/s": "%1 Mbit/s",
    "%1 kbit/s": "%1 kbit/s",
    "stream lost — reconnecting (%1)": "Stream verloren — verbinde neu (%1)",

    # ── decoder options and signal ──
    "Hardware (recommended)": "Hardware (empfohlen)",
    "Hardware, driver's choice": "Hardware, Treiberwahl",
    "“Recommended” names the decoder explicitly so that decoding and drawing "
    "stay on the same graphics API. Left to itself, mpv may decode through one "
    "API and draw through another, which on some cards turns the picture solid "
    "green.\n\n"
    "If the picture is broken, try the others in turn. “Software only” always "
    "works but costs a whole processor core at full resolution.":
        "„Empfohlen“ benennt den Decoder ausdrücklich, damit Dekodieren und "
        "Zeichnen auf derselben Grafik-API bleiben. Sich selbst überlassen, "
        "dekodiert mpv womöglich über die eine API und zeichnet über die "
        "andere — auf manchen Karten wird das Bild dann komplett grün.\n\n"
        "Bei kaputtem Bild die anderen der Reihe nach probieren. „Nur "
        "Software“ funktioniert immer, kostet bei voller Auflösung aber einen "
        "ganzen Prozessorkern.",
    "Mobile data": "Mobilfunk",
    "Wired": "Kabel",
    "%1 — strength unknown": "%1 — Stärke unbekannt",
    "%1 — %2 of %3": "%1 — %2 von %3",

    # ── stream health ──
    "WEAK SIGNAL": "SCHWACHES SIGNAL",
    "BAD STREAM": "GESTÖRTER STROM",
    "stream ended (%1) — reconnecting":
        "Stream beendet (%1) — verbinde neu",
    "Open the &log file": "&Protokolldatei öffnen",
    "What the players and the cameras reported. Worth attaching to a bug "
    "report.":
        "Was die Wiedergabe und die Kameras gemeldet haben. Gehört an einen "
        "Fehlerbericht.",
    "Nothing logged yet.": "Noch nichts protokolliert.",

    # ── bitrate warning ──
    "Bit rate looks too low": "Bitrate wirkt zu niedrig",
    "<b>%1 kbit/s is very little for %2.</b>":
        "<b>%1 kbit/s sind sehr wenig für %2.</b>",
    "At this ratio the camera's encoder tends to emit damaged frames, which "
    "arrive as green blocks or a picture that freezes — not a network fault, "
    "and not something leolink can repair fully.\n\n"
    "Either raise the bit rate or lower the resolution.":
        "In diesem Verhältnis erzeugt der Encoder der Kamera beschädigte "
        "Bilder, die als grüne Flächen oder stehendes Bild ankommen — kein "
        "Netzwerkfehler, und von leolink nicht vollständig zu reparieren.\n\n"
        "Entweder die Bitrate erhöhen oder die Auflösung senken.",
    "Apply anyway": "Trotzdem anwenden",

    "camera is reconfiguring…": "Kamera stellt sich um…",

    # ── tests, condition, firmware, storage ──
    "Send a test e-mail": "Test-E-Mail senden",
    "Test the FTP upload": "FTP-Upload testen",
    "Asking the camera to send a test e-mail…":
        "Bitte die Kamera, eine Test-E-Mail zu senden…",
    "Asking the camera to try the FTP server…":
        "Bitte die Kamera, den FTP-Server zu versuchen…",
    "%1: the camera reported success.": "%1: Die Kamera meldet Erfolg.",
    "Condition": "Zustand",
    "Processor load %1%": "Prozessorlast %1 %",
    "Encoder load %1%": "Encoder-Last %1 %",
    "Network throughput %1 kbit/s": "Netzdurchsatz %1 kbit/s",
    "The camera is at its limit. Lowering the resolution or frame rate will "
    "steady it.":
        "Die Kamera ist am Anschlag. Eine niedrigere Auflösung oder Bildrate "
        "beruhigt sie.",
    "Firmware": "Firmware",
    "Not checked.": "Nicht geprüft.",
    "Check for updates": "Nach Aktualisierung suchen",
    "Asking Reolink…": "Frage bei Reolink an…",
    "Install update": "Aktualisierung einspielen",
    "Update available: %1": "Aktualisierung verfügbar: %1",
    "The firmware is up to date.": "Die Firmware ist aktuell.",
    "Install firmware": "Firmware einspielen",
    "<b>Update the firmware on %1?</b>": "<b>Firmware auf %1 aktualisieren?</b>",
    "The camera downloads the update itself and restarts. It will be "
    "unreachable for several minutes.\n\n"
    "Do not cut its power during the update — a camera interrupted mid-flash "
    "usually needs sending back.":
        "Die Kamera lädt die Aktualisierung selbst und startet neu. Sie ist "
        "dabei mehrere Minuten nicht erreichbar.\n\n"
        "Währenddessen keinesfalls die Stromversorgung trennen — eine mitten "
        "im Schreibvorgang unterbrochene Kamera muss meist eingeschickt "
        "werden.",
    "Install": "Einspielen",
    "Upgrading. The camera will restart on its own and be unreachable for "
    "several minutes. Do not cut its power.":
        "Wird eingespielt. Die Kamera startet von selbst neu und ist einige "
        "Minuten nicht erreichbar. Strom nicht trennen.",
    "Storage": "Speicher",
    "Format the SD card": "SD-Karte formatieren",
    "Formatting erases every recording on the card. There is no undo and no "
    "confirmation from the camera afterwards.":
        "Formatieren löscht jede Aufnahme auf der Karte. Das lässt sich nicht "
        "rückgängig machen, und die Kamera bestätigt es hinterher nicht.",
    "<b>Erase everything on the card in %1?</b>":
        "<b>Alles auf der Karte in %1 löschen?</b>",
    "Every recording on the card is deleted. This cannot be undone, and "
    "nothing that has not already been downloaded can be recovered.":
        "Jede Aufnahme auf der Karte wird gelöscht. Das ist unumkehrbar, und "
        "was nicht bereits heruntergeladen wurde, ist verloren.",
    "Erase": "Löschen",
    "Formatting…": "Formatiere…",
    "The card has been formatted.": "Die Karte wurde formatiert.",
    "Factory reset is not offered here. It clears the network settings as "
    "well, and a camera that has forgotten its Wi-Fi has to be fetched down "
    "and reset by hand.":
        "Werksreset gibt es hier nicht. Er löscht auch die Netzwerk"
        "einstellungen, und eine Kamera, die ihr WLAN vergessen hat, muss man "
        "herunterholen und von Hand einrichten.",

    # ── users ──
    "Users": "Benutzer",
    "Rights": "Rechte",
    "Administrator": "Administrator",
    "Viewer": "Betrachter",
    "Add…": "Hinzufügen…",
    "Change password…": "Passwort ändern…",
    "Delete": "Löschen",
    "New user": "Neuer Benutzer",
    "User name": "Benutzername",
    "Password for %1": "Passwort für %1",
    "Creating %1…": "Lege %1 an…",
    "Change password": "Passwort ändern",
    "New password for %1": "Neues Passwort für %1",
    "Changing the password for %1…": "Ändere das Passwort für %1…",
    "This is the account leolink uses": "Das ist das Konto, das leolink nutzt",
    "Change it here and leolink will be locked out until the new password is "
    "entered under Cameras as well.":
        "Wird es hier geändert, ist leolink ausgesperrt, bis das neue Passwort "
        "auch unter Kameras eingetragen ist.",
    "Cannot delete this account": "Dieses Konto lässt sich nicht löschen",
    "leolink is signed in as “%1”. Deleting it would cut the connection to "
    "this camera immediately.":
        "leolink ist als „%1“ angemeldet. Ein Löschen würde die Verbindung zu "
        "dieser Kamera sofort kappen.",
    "Delete user": "Benutzer löschen",
    "Delete “%1” from the camera?": "„%1“ von der Kamera löschen?",
    "Deleting %1…": "Lösche %1…",
    "Done.": "Fertig.",
    "These are accounts on the camera, not in leolink. A viewer account can "
    "watch but not change anything — worth using for anything that only needs "
    "to see the picture, so a stored password cannot be turned against the "
    "camera's settings.":
        "Das sind Konten auf der Kamera, nicht in leolink. Ein Betrachterkonto "
        "darf zusehen, aber nichts ändern — sinnvoll überall dort, wo nur das "
        "Bild gebraucht wird, damit ein gespeichertes Passwort nicht gegen die "
        "Einstellungen der Kamera verwendet werden kann.",
    "camera is reconfiguring… %1 s": "Kamera stellt sich um… %1 s",

    # ── errors from the camera ──
    "File format not recognised.": "Dateiformat nicht erkannt.",
    "Invalid input.": "Ungültige Eingabe.",
    "No free connections — the camera allows only a few sessions at a time.":
        "Keine freien Verbindungen — die Kamera erlaubt nur wenige Sitzungen "
        "gleichzeitig.",
    "Session expired.": "Sitzung abgelaufen.",
    "Wrong user name or password.": "Benutzername oder Passwort falsch.",
    "Timed out.": "Zeitüberschreitung.",
    "This firmware does not support that command.":
        "Diese Firmware kennt den Befehl nicht.",
    "Could not read the configuration.":
        "Die Konfiguration ließ sich nicht lesen.",
    "Could not verify the configuration.":
        "Die Konfiguration ließ sich nicht prüfen.",
    "Subsystem unavailable — typically no SD card fitted.":
        "Teilsystem nicht verfügbar — meist steckt keine SD-Karte.",
    "Not permitted — this model lacks the hardware.":
        "Nicht möglich — diesem Modell fehlt die Hardware dafür.",
    "Account invalid, log in again.":
        "Konto ungültig, bitte neu anmelden.",
    "User name already taken.": "Benutzername ist bereits vergeben.",
    "Maximum number of users reached.": "Maximale Benutzerzahl erreicht.",
    "Camera busy, try again shortly.":
        "Kamera beschäftigt, bitte gleich noch einmal versuchen.",
    "IP address conflict.": "IP-Adresskonflikt.",
    "Configuration test failed.": "Konfigurationstest fehlgeschlagen.",
    "FTP login failed.": "FTP-Anmeldung fehlgeschlagen.",
    "FTP could not create the directory.":
        "FTP konnte das Verzeichnis nicht anlegen.",
    "FTP upload failed.": "FTP-Übertragung fehlgeschlagen.",
    "FTP could not reach the server.": "FTP erreichte den Server nicht.",
    "Camera reported error %1.": "Die Kamera meldet Fehler %1.",
    "Cannot reach %1: %2": "%1 nicht erreichbar: %2",
    "Unexpected reply from %1.": "Unerwartete Antwort von %1.",
    "Login returned no token.": "Die Anmeldung lieferte kein Token.",
    "Snapshot failed.": "Standbild fehlgeschlagen.",
    "ONVIF subscription failed.": "ONVIF-Abonnement fehlgeschlagen.",
}

# Plural forms need one <numerusform> per German plural (singular, plural).
PLURALS: dict[str, list[str]] = {
    ", %n access point(s)": [", %n Zugangspunkt", ", %n Zugangspunkte"],
    "Heard from %n access point(s) — one network, several nodes. The strongest "
    "is what is shown.": [
        "Von %n Zugangspunkt empfangen — ein Netz, mehrere Knoten. Angezeigt "
        "wird der stärkste.",
        "Von %n Zugangspunkten empfangen — ein Netz, mehrere Knoten. Angezeigt "
        "wird der stärkste."],
    "%n network(s) found, strongest first.": [
        "%n Netz gefunden, stärkstes zuerst.",
        "%n Netze gefunden, stärkstes zuerst."],
    "Asking about %n command(s)…": ["Frage %n Befehl ab…", "Frage %n Befehle ab…"],
    "%n area(s) blanked": ["%n Bereich geschwärzt", "%n Bereiche geschwärzt"],
    "%n area(s), switched off": ["%n Bereich, abgeschaltet",
                                 "%n Bereiche, abgeschaltet"],
    "%n hour(s) a week.": ["%n Stunde pro Woche.", "%n Stunden pro Woche."],

    "%n camera(s) live": ["%n Kamera live", "%n Kameras live"],
    "Saved %n snapshot(s)": ["%n Standbild gespeichert",
                             "%n Standbilder gespeichert"],
    "Found %n device(s)…": ["%n Gerät gefunden…", "%n Geräte gefunden…"],
    "%n recording(s) found.": ["%n Aufnahme gefunden.", "%n Aufnahmen gefunden."],
    "%n network(s) found.": ["%n Netzwerk gefunden.", "%n Netzwerke gefunden."],
    "%n damaged frame(s) in the last ten seconds.\n\n"
    "Usually a weak Wi-Fi signal, or a bitrate set too low for the resolution. "
    "leolink repairs what it can — this is what it could not.": [
        "%n beschädigtes Bild in den letzten zehn Sekunden.\n\n"
        "Meist ein schwaches WLAN-Signal oder eine für die Auflösung zu "
        "niedrige Bitrate. leolink repariert, was es kann — das hier ging "
        "nicht mehr.",
        "%n beschädigte Bilder in den letzten zehn Sekunden.\n\n"
        "Meist ein schwaches WLAN-Signal oder eine für die Auflösung zu "
        "niedrige Bitrate. leolink repariert, was es kann — das hier ging "
        "nicht mehr."],
}


def main() -> int:
    if not TS_FILE.exists():
        print(f"{TS_FILE} not found — run the update_translations target first.",
              file=sys.stderr)
        return 1

    text = TS_FILE.read_text(encoding="utf-8")
    filled = 0
    missing: list[str] = []

    def unescape(value: str) -> str:
        return (value.replace("&lt;", "<").replace("&gt;", ">")
                     .replace("&quot;", '"').replace("&apos;", "'")
                     .replace("&amp;", "&"))

    def replace(match: re.Match) -> str:
        nonlocal filled
        block = match.group(0)
        source_match = re.search(r"<source>(.*?)</source>", block, re.S)
        if not source_match:
            return block
        source = unescape(source_match.group(1))

        if source in PLURALS:
            forms = "".join(f"<numerusform>{escape(f)}</numerusform>"
                            for f in PLURALS[source])
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{forms}</translation>", block, flags=re.S)

        if source in GERMAN:
            filled += 1
            return re.sub(r"<translation[^>]*>.*?</translation>",
                          f"<translation>{escape(GERMAN[source])}</translation>",
                          block, flags=re.S)

        missing.append(source)
        return block

    text = re.sub(r"<message[^>]*>.*?</message>", replace, text, flags=re.S)
    TS_FILE.write_text(text, encoding="utf-8")

    print(f"translated {filled} messages in {TS_FILE.name}")
    if missing:
        print(f"{len(missing)} still untranslated (English will be shown):")
        for m in missing[:20]:
            print(f"  · {m[:70]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
